-- Part 5 of 5 - run this in the Supabase SQL Editor AFTER the previous parts.
-- Safe to re-run: every statement in the source file is idempotent (on
-- conflict do nothing / coalesce jsonb merge).

-- Attaches real legacy images to the 148 migrated Stays properties
-- (node_media role='hero'/'gallery') and their real room/villa photos
-- (accommodation_room_media). No new media_assets rows — every id below
-- already exists from 20250115000100_full_legacy_image_library.sql.
-- GENERATED FILE, regenerate with:
--   node scripts/attach-stays-images.mjs

-- Aaaveee-Natures-Paradise (Aaaveee Nature's Paradise Island Resort Maldives)

insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '7db2ab8b-2c6a-b096-9272-307ee3ffead5', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'W Maldives Island Resort Maldives' and r.name = 'Sunrise Beach Villa' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, 'cea6f1a7-154c-22b9-452f-fd5754cc6707', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'W Maldives Island Resort Maldives' and r.name = 'Sunrise Beach Villa' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, 'cc9831bc-9be8-7aee-9e4a-ff0448130020', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'W Maldives Island Resort Maldives' and r.name = 'Over Water Pool Villa' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '46fb77fd-40f6-b1a8-9ee0-68473922814e', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'W Maldives Island Resort Maldives' and r.name = 'Over Water Pool Villa' on conflict (room_id, media_id) do nothing;
-- Amra-Palace (Amra Palace Island Hotel Maldives)
insert into node_media (node_id, media_id, role, sort_order) select id, '4de1ca29-81f0-2f11-82eb-03b2182d2aa5', 'hero', 0 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '64b667b8-43eb-ee1b-1d6e-b0d797be2d77', 'gallery', 0 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '61031541-c3a1-2ed9-71e5-ffa67797c02d', 'gallery', 1 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'ba1f7043-f7d9-4fd1-c30e-ec3cfd5e2892', 'gallery', 2 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'bad2036d-8878-cc6b-fa8c-954d164a78c3', 'gallery', 3 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'ab5e52ca-1e1f-d5c5-a05a-9992d6c4bc6c', 'gallery', 4 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '4511c4d4-c7c5-d3c7-004c-bf1a0a85c54a', 'gallery', 5 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '6f439a93-a5c4-7ffa-1196-a4eace31ea25', 'gallery', 6 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '2756c3d9-7bdd-d8bf-a4c4-d2e9a96b31ba', 'gallery', 7 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '0d4f8e93-f305-ac50-2dca-187d99b17d2e', 'gallery', 8 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'db6cc26a-47d9-7e49-db5e-5d4331cc0b74', 'gallery', 9 from nodes where node_type = 'accommodation' and title = 'Amra Palace Island Hotel Maldives' on conflict (node_id, media_id, role) do nothing;

-- arena-maafushi (Arena Beach Hotel Maafushi Maldives)
insert into node_media (node_id, media_id, role, sort_order) select id, '9575e9f7-bf40-8629-751f-2297690462b3', 'hero', 0 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'b38342d6-8b73-dbb6-b35b-8cfabdfee69c', 'gallery', 0 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '17e55473-8b04-2c8b-1ad2-8fd99df3791c', 'gallery', 1 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '73bdd20e-bb4e-ac5f-46e5-574c83dcae71', 'gallery', 2 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3af9fd20-b9d1-c228-cf4c-8187c70f9eed', 'gallery', 3 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'e3128603-5cff-038a-c26a-6b07dfd3d9fe', 'gallery', 4 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '9e668f08-f3cb-2ec2-5c70-17b293e7d94f', 'gallery', 5 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '023e19a1-b4fb-883c-2152-0271b1f9849d', 'gallery', 6 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3af59795-b719-7159-0238-6b1f068348d5', 'gallery', 7 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3ec84a6c-1472-e6d7-4810-b826a3c0994f', 'gallery', 8 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f2f6261b-93d7-bd27-73f9-b04b4e4b4fc5', 'gallery', 9 from nodes where node_type = 'accommodation' and slug = 'arena-beach-hotel' on conflict (node_id, media_id, role) do nothing;

insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '126b6616-98fc-f3c7-1804-814acf9e425f', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and slug = 'arena-beach-hotel' and r.name = 'Standard Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, 'acbe08c4-6032-bb04-cf0a-bd9ac058baee', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and slug = 'arena-beach-hotel' and r.name = 'Standard Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '7261cdbc-1f54-7562-bcdc-8c7f71bf3aec', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and slug = 'arena-beach-hotel' and r.name = 'Double Sea View Balcony Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '896d02c3-e824-4b5c-7b30-b7fdda73c0d6', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and slug = 'arena-beach-hotel' and r.name = 'Double Sea View Balcony Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '7b24dfd6-0b9a-8e21-0fbc-6959622c2f58', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and slug = 'arena-beach-hotel' and r.name = 'Balcony Sea View Tripple Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '30682d41-e659-b5db-b5ee-82797f1d9291', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and slug = 'arena-beach-hotel' and r.name = 'Balcony Sea View Tripple Room' on conflict (room_id, media_id) do nothing;
-- casa-retreat (casa-retreat)
insert into node_media (node_id, media_id, role, sort_order) select id, '5e8141f9-961f-1779-f7d4-360b47fbf502', 'hero', 0 from nodes where node_type = 'accommodation' and title = 'casa-retreat' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '16191afa-c2ba-eb04-b311-1770f7ce466e', 'gallery', 0 from nodes where node_type = 'accommodation' and title = 'casa-retreat' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f1c7fe9e-2b19-e0a5-2869-229a56d7b897', 'gallery', 1 from nodes where node_type = 'accommodation' and title = 'casa-retreat' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '61be21cd-2da8-85ea-6d4f-8842c6909eae', 'gallery', 2 from nodes where node_type = 'accommodation' and title = 'casa-retreat' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'c0a70094-cdaa-d2da-a7aa-b9a3753f5b4b', 'gallery', 3 from nodes where node_type = 'accommodation' and title = 'casa-retreat' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a9ccb950-cccf-1931-b293-b2188762d283', 'gallery', 4 from nodes where node_type = 'accommodation' and title = 'casa-retreat' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '68c6e8d6-dd88-3c41-3c84-303d2fbc4f68', 'gallery', 5 from nodes where node_type = 'accommodation' and title = 'casa-retreat' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'b102a560-22f4-5b73-73a6-97ae191d80da', 'gallery', 6 from nodes where node_type = 'accommodation' and title = 'casa-retreat' on conflict (node_id, media_id, role) do nothing;

insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, 'c084e92e-d9d5-6706-e040-b1c248005ef0', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'casa-retreat' and r.name = 'Standard Room' on conflict (room_id, media_id) do nothing;
-- gaafaru-view-inn-maldives (Gaafari view inn Hotel Maldives)
insert into node_media (node_id, media_id, role, sort_order) select id, 'c26b5f9c-817a-5a4c-d17c-da1818e022d3', 'hero', 0 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'faad26ef-67c4-6ab0-a91b-25a53533f73d', 'gallery', 0 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '7218d4a0-0fbb-dde6-1809-4719fb818bbc', 'gallery', 1 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3a5a4e7c-9892-7d6b-3728-5da3bc7ee7c1', 'gallery', 2 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '0a7852ca-5fe7-a2a2-8694-8ac5d0646f00', 'gallery', 3 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '608842c5-b696-d663-5daf-6f733fb56cf3', 'gallery', 4 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '68161a53-748d-0416-8661-6fd0d2f01ba8', 'gallery', 5 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '19228a28-1c53-7f8a-eedc-a855eddc13a2', 'gallery', 6 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '86b2559f-6dbb-7d10-9eda-be3f75bf6459', 'gallery', 7 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'c4b5f217-2f67-7f9f-3342-ab4217af1dc5', 'gallery', 8 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a12acd2c-c5ea-a1d0-40df-4f2f14fc3a92', 'gallery', 9 from nodes where node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' on conflict (node_id, media_id, role) do nothing;

insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '61697551-aff2-1c00-2816-40e2043aee9c', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Gaafari view inn Hotel Maldives' and r.name = 'Room' on conflict (room_id, media_id) do nothing;
-- island-break-fulidhoo (Island Break Fulidhoo Maldives)
insert into node_media (node_id, media_id, role, sort_order) select id, '504ac1e7-9d94-cb41-97a1-85c4fb6a7cee', 'hero', 0 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'cbc120c9-f05e-5fd3-81d6-f1282c55a664', 'gallery', 0 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f046a205-7663-64eb-c29f-4608a443c66a', 'gallery', 1 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f6cb8782-dcb0-a374-d749-8620a365f01f', 'gallery', 2 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '9faba721-9046-62ce-a3a4-b7d5d77dac1f', 'gallery', 3 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '24863eea-892d-a207-5b5e-d58893ffb04a', 'gallery', 4 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '0562d4f1-a894-c391-e582-bf3e11fe002d', 'gallery', 5 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '5b96265c-4bc5-cc61-ab6f-7a6b070e1634', 'gallery', 6 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '0f427e3d-23d9-a1a3-5e59-541d8ff112e5', 'gallery', 7 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3cb775e6-8696-4723-5c0e-373ac72a2b56', 'gallery', 8 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '6caf73c1-d544-2a99-0961-58d40ed808f4', 'gallery', 9 from nodes where node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' on conflict (node_id, media_id, role) do nothing;

insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '0b03b161-b441-531b-e254-289878f12036', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' and r.name = 'Ground Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '2473c475-d43a-c5ea-71bd-89796fae73e7', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' and r.name = 'Ground Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '7a25e7ec-c409-39ee-105b-6d2bf565f51c', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' and r.name = 'Luxury Coconut Suit with Balcony' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '24fe181a-2324-8303-096c-dca9322c4330', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' and r.name = 'Luxury Coconut Suit with Balcony' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, 'fe1071dc-6688-3c4f-e484-9854208ca359', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' and r.name = 'Luxury Coconut Suit Triple Room with Balcony' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, 'cbd8d314-4fda-e72c-95a9-68da420c3b73', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' and r.name = 'Luxury Coconut Suit Triple Room with Balcony' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '39033be8-fe5d-dba4-27e8-2ca69054115c', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' and r.name = 'Luxury Coconut Suit with Balcony Twin Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '2819e085-4546-10f9-76f2-fea112505919', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Island Break Fulidhoo Maldives' and r.name = 'Luxury Coconut Suit with Balcony Twin Room' on conflict (room_id, media_id) do nothing;
-- kaanibeach-maafushi (Kaani Beach Hotel Maafushi Maldives)
insert into node_media (node_id, media_id, role, sort_order) select id, '57d97e22-92a2-a86e-45b0-b3d487546305', 'hero', 0 from nodes where node_type = 'accommodation' and slug = 'kaani-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '9e7a83fe-0c44-9ef9-95c1-813b9cf7fa53', 'gallery', 0 from nodes where node_type = 'accommodation' and slug = 'kaani-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f747bc41-b4ca-66a0-e1a6-804d2332a410', 'gallery', 1 from nodes where node_type = 'accommodation' and slug = 'kaani-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'd19a0ea9-d00a-3e74-6ca0-cff793306732', 'gallery', 2 from nodes where node_type = 'accommodation' and slug = 'kaani-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a90df2c7-481e-7f55-18e7-bc4a0748b911', 'gallery', 3 from nodes where node_type = 'accommodation' and slug = 'kaani-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a42f6b6a-be87-5b65-2770-cb1f24fe13e5', 'gallery', 4 from nodes where node_type = 'accommodation' and slug = 'kaani-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '15a66c60-01db-c6a6-7ed4-bddab90df80b', 'gallery', 5 from nodes where node_type = 'accommodation' and slug = 'kaani-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '9bbead44-417f-23d5-a02d-e7741f6d21ac', 'gallery', 6 from nodes where node_type = 'accommodation' and slug = 'kaani-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '84b72022-368a-83e6-0b30-07803a5ea42e', 'gallery', 7 from nodes where node_type = 'accommodation' and slug = 'kaani-beach-hotel' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '147831aa-9752-c56c-c276-1d29a6144e8a', 'gallery', 8 from nodes where node_type = 'accommodation' and slug = 'kaani-beach-hotel' on conflict (node_id, media_id, role) do nothing;

insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '2dffb5db-f8e4-5860-bf6e-4f8cd991f0c6', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and slug = 'kaani-beach-hotel' and r.name = 'Deluxe Sea View Balcony Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '55f5f867-c6f9-331c-f2f6-1cf96535721b', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and slug = 'kaani-beach-hotel' and r.name = 'Deluxe Sea View Balcony Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '745db38b-4f24-91c9-d270-a28aa8da4d2c', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and slug = 'kaani-beach-hotel' and r.name = 'Tripple Sea View Balcony Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '895ccc7a-dfe7-3751-09d0-38e3d2739bd1', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and slug = 'kaani-beach-hotel' and r.name = 'Tripple Sea View Balcony Room' on conflict (room_id, media_id) do nothing;
-- maagiri (Maagiri Hotel Male Maldives)
insert into node_media (node_id, media_id, role, sort_order) select id, 'efe80858-d3a2-c0c5-91d4-5ae8f36ea30c', 'hero', 0 from nodes where node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '10b0b4b6-714a-c818-3c5e-c0e72cea0f8b', 'gallery', 0 from nodes where node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '1dcfd9c6-2f8d-f907-9e21-c7a16d8ed6ac', 'gallery', 1 from nodes where node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '33ca3e65-25b1-a571-9c1c-48f1c1adc69b', 'gallery', 2 from nodes where node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '262c6e46-605b-4654-72d4-634f8ba3da9b', 'gallery', 3 from nodes where node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '048f12a0-60b9-10cc-3c5d-ecfc3deb8c67', 'gallery', 4 from nodes where node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '01879936-de3a-7989-5be8-b7c84b320d0c', 'gallery', 5 from nodes where node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '45569577-e8c0-8092-a5d7-409c43d2a6e7', 'gallery', 6 from nodes where node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'e1f40a48-3481-ab89-8047-8d4bea9cfe52', 'gallery', 7 from nodes where node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;

insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '25337ec5-5194-8ca8-cc92-82177e6a9f9d', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' and r.name = 'Premier Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '3c27bee7-c36c-8b9f-0528-c87f12b8e90c', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' and r.name = 'Premier Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '6e1b971b-a8d9-b814-1805-56b4e3a6d898', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' and r.name = 'Junior Suit' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '1b81005e-77bc-c697-56ac-4621559d0880', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Maagiri Hotel Male Maldives' and r.name = 'Junior Suit' on conflict (room_id, media_id) do nothing;
-- mantha-view-hotel (Mantha view Hotel Maldives)
insert into node_media (node_id, media_id, role, sort_order) select id, 'a166a45d-13b2-2809-13ea-72f990bf1da1', 'hero', 0 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a8e034a9-95fa-aad2-a48e-8c6e70a4491f', 'gallery', 0 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a428e423-ebb9-a8f8-3721-28d5f122c756', 'gallery', 1 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'aa70bde9-0ac7-7c50-cfbf-efc3acb9c4ae', 'gallery', 2 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '7008fd8c-31f6-8609-dba5-6801d6305995', 'gallery', 3 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8f9644b8-d5e5-e7d2-6c1c-772116afd9d0', 'gallery', 4 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '46b0f061-fb75-384e-5a83-ab84a5bc390b', 'gallery', 5 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'cb1f311b-f026-52e0-b054-ddea1b81009d', 'gallery', 6 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3b90a524-c162-d1c3-8d05-53593ec6edac', 'gallery', 7 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '7a1964f7-97c0-92b5-cc99-8fe60a426a06', 'gallery', 8 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'eef40f4b-6ffe-dc76-9c69-f2c0a383501d', 'gallery', 9 from nodes where node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' on conflict (node_id, media_id, role) do nothing;

insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, 'a418823c-270d-5350-f8b0-e470b9ad98a5', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Mantha view Hotel Maldives' and r.name = 'Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, 'f4f07785-3cbe-9e79-cce2-2e259164823f', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'reveries-village' and r.name = 'Deluxe Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '6690819d-d030-8960-c761-70d0fbdd8416', 1 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'reveries-village' and r.name = 'Deluxe Room' on conflict (room_id, media_id) do nothing;
-- rosemery-maafushi (rosemery-maafushi)
insert into node_media (node_id, media_id, role, sort_order) select id, 'fd61f1ad-a114-e629-5a28-2b1051f5df36', 'hero', 0 from nodes where node_type = 'accommodation' and title = 'rosemery-maafushi' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '19b85eef-1f7e-10c0-d85e-04cf6beed688', 'gallery', 0 from nodes where node_type = 'accommodation' and title = 'rosemery-maafushi' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'bf0c0018-0ed4-bbb8-5159-cd94bcea6f1d', 'gallery', 1 from nodes where node_type = 'accommodation' and title = 'rosemery-maafushi' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '60f3e5e6-cbae-ed05-f25e-befd0dfd011e', 'gallery', 2 from nodes where node_type = 'accommodation' and title = 'rosemery-maafushi' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '71936a5f-6242-2af9-41ec-0fb8ce8c5352', 'gallery', 3 from nodes where node_type = 'accommodation' and title = 'rosemery-maafushi' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a78824af-1cef-0cc0-a45b-0dbb9006686c', 'gallery', 4 from nodes where node_type = 'accommodation' and title = 'rosemery-maafushi' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '0be8c070-e906-6845-8394-2aa729166814', 'gallery', 5 from nodes where node_type = 'accommodation' and title = 'rosemery-maafushi' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'e5d79447-ee74-1493-11af-ddaf92eb7316', 'gallery', 6 from nodes where node_type = 'accommodation' and title = 'rosemery-maafushi' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '98ab6a7d-5772-07bc-df57-0a8814ee7722', 'gallery', 7 from nodes where node_type = 'accommodation' and title = 'rosemery-maafushi' on conflict (node_id, media_id, role) do nothing;

insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, 'cfc2fb1a-cc28-949a-f4e9-d81dbe769e2a', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'rosemery-maafushi' and r.name = 'Double Balcony Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '2eff104e-1b9c-328e-58b8-1766846f39f9', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'rosemery-maafushi' and r.name = 'Tripple Balcony Room' on conflict (room_id, media_id) do nothing;
-- surfview-male (Surfview Hotel Male Maldives)
insert into node_media (node_id, media_id, role, sort_order) select id, '7838258e-6e3f-4ef1-a5f5-15419eb78d13', 'hero', 0 from nodes where node_type = 'accommodation' and title = 'Surfview Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a049c777-a314-d092-c6e8-5fe4093e28eb', 'gallery', 0 from nodes where node_type = 'accommodation' and title = 'Surfview Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '9e16e0aa-d769-2b25-c255-d0235d25a94b', 'gallery', 1 from nodes where node_type = 'accommodation' and title = 'Surfview Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'b6d5ca8c-d13f-a1c5-3f3e-135a40e8ae40', 'gallery', 2 from nodes where node_type = 'accommodation' and title = 'Surfview Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'd466fbad-97b7-f828-349d-e8786f36c457', 'gallery', 3 from nodes where node_type = 'accommodation' and title = 'Surfview Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '4055ef6a-4e8c-f008-dae4-266b835f422b', 'gallery', 4 from nodes where node_type = 'accommodation' and title = 'Surfview Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '6f102954-2760-c153-6183-2c6fc9d16b2d', 'gallery', 5 from nodes where node_type = 'accommodation' and title = 'Surfview Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'da8347ad-9eb7-c81d-5a51-50043e40ab3d', 'gallery', 6 from nodes where node_type = 'accommodation' and title = 'Surfview Hotel Male Maldives' on conflict (node_id, media_id, role) do nothing;

insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, '81343a02-36d7-c1ea-ccd7-0c1ff3562344', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Surfview Hotel Male Maldives' and r.name = 'Superior Room' on conflict (room_id, media_id) do nothing;
insert into accommodation_room_media (room_id, media_id, sort_order) select r.id, 'd99512c8-1da1-248a-ae79-b9659f652544', 0 from accommodation_rooms r join nodes n on n.id = r.accommodation_id where n.node_type = 'accommodation' and title = 'Surfview Hotel Male Maldives' and r.name = 'Sea View Room' on conflict (room_id, media_id) do nothing;
