// Generated by `supabase gen types typescript`.
// Regenerate after any migration change:
//   npx supabase gen types typescript --db-url "$DATABASE_URL" > src/types/database.ts
//
// This placeholder exists so the Supabase client utilities type-check before
// a live/local database is available to generate against. It was NOT
// regenerated from the verified schema in this task: `supabase gen types
// typescript --db-url` shells out to Docker even for a plain --db-url
// connection, and this sandbox has no Docker daemon available (see the
// implementation report for details). The migrations themselves were fully
// applied and verified against a local Postgres instance — only this
// generated-types step is deferred.
//
// Once a real Supabase project exists (or Docker is available locally),
// regenerate with the command above and this file becomes fully typed.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
