-- Maldives Attractions: real, sourced points of interest (location_type = 'poi'),
-- the same architecture already used for dive sites and surf breaks — no new
-- table, no duplicate entity model. Source:
--   data/maldives/attractions/attractions.json
--   data/maldives/attractions/SOURCES.md
-- GENERATED FILE, regenerate with:
--   node scripts/generate-attractions-seed.mjs

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'hukuru-miskiy-old-friday-mosque', 'Hukuru Miskiy (Old Friday Mosque)', 'A UNESCO-listed 17th-century coral-stone mosque in Malé, famed for its intricate carvings and lacquer work.', 'published', 'Hukuru Miskiy (Old Friday Mosque) | Maldives Attractions | MTG', 'A UNESCO-listed 17th-century coral-stone mosque in Malé, famed for its intricate carvings and lacquer work.', '{"attraction_type":"religious","best_for":"History and architecture enthusiasts","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"Male Friday Mosque, also known as Hukuru Miskiy, is one of the oldest and most significant mosques in the Maldives. Built in 1658, it is renowned for its intricate coral stone architecture, traditional wood carvings and lacquer work, and is a UNESCO World Heritage tentative site. Visitors can explore the mosque''s ancient inscriptions, tombstones and architectural features to learn about the history and cultural heritage of the Maldives. The mosque is still active, so dress modestly and respect local customs while visiting."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'hukuru_miskiy_old_friday_mosque'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'hukuru-miskiy-old-friday-mosque' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'hukuru-miskiy-old-friday-mosque');
insert into node_media (node_id, media_id, role, sort_order) select id, '48013214-6420-c4ce-bd60-acac594d6ea6', 'hero', 0 from nodes where node_type = 'location' and slug = 'hukuru-miskiy-old-friday-mosque' on conflict (node_id, media_id, role) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'national-museum-male', 'The National Museum', 'The Maldives'' National Museum, housed in a former royal palace in Sultan Park, Malé.', 'published', 'The National Museum | Maldives Attractions | MTG', 'The Maldives'' National Museum, housed in a former royal palace in Sultan Park, Malé.', '{"attraction_type":"museum","best_for":"Families and history buffs","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"The National Museum of Maldives is located in Sultan Park, housed in a former royal palace. The museum showcases the rich history and culture of the Maldives, with exhibits ranging from ancient artifacts and royal regalia to traditional costumes and weapons. Visitors can learn about the Maldives'' history, from its Buddhist period to the Islamic era, through the museum''s extensive collection — an excellent stop for families and history buffs."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'national_museum_male'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'national-museum-male' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'national-museum-male');
insert into node_media (node_id, media_id, role, sort_order) select id, '271b212c-d8c7-9a36-c9c3-1c79dd7753f6', 'hero', 0 from nodes where node_type = 'location' and slug = 'national-museum-male' on conflict (node_id, media_id, role) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'mulee-aage-presidents-palace', 'Mulee''aage (The President''s Palace)', 'The official residence of the President of the Maldives, an early-20th-century colonial-style palace in Malé.', 'published', 'Mulee''aage (The President''s Palace) | Maldives Attractions | MTG', 'The official residence of the President of the Maldives, an early-20th-century colonial-style palace in Malé.', '{"attraction_type":"landmark","best_for":"A quick photo stop on a Malé walking tour","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"Mulee''aage, the official residence of the President of the Maldives, is a striking example of colonial architecture in Malé. Built in the early 20th century, the palace is known for its elaborate carvings, vibrant colors and well-manicured gardens. Visitors aren''t allowed inside, but the exterior offers a great photography spot and a popular stop on walking tours of Malé."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'mulee_aage_presidents_palace'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'mulee-aage-presidents-palace' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'mulee-aage-presidents-palace');
insert into node_media (node_id, media_id, role, sort_order) select id, 'e8542e01-e2ad-eccc-ce78-d87f37e55d7a', 'hero', 0 from nodes where node_type = 'location' and slug = 'mulee-aage-presidents-palace' on conflict (node_id, media_id, role) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'sultan-park', 'Sultan Park and Rasrani Bageecha', 'A lush green park in the heart of Malé, once part of the royal palace grounds and home to the National Museum.', 'published', 'Sultan Park and Rasrani Bageecha | Maldives Attractions | MTG', 'A lush green park in the heart of Malé, once part of the royal palace grounds and home to the National Museum.', '{"attraction_type":"park","best_for":"Families wanting a relaxed break in central Malé","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"Sultan Park, also known as Rasrani Bageecha, is a lush green space in the heart of Malé, offering a peaceful retreat from the city''s hustle and bustle. The park was once part of the royal palace grounds and now features well-maintained gardens, playgrounds and water features. It''s an ideal spot for families to relax, with plenty of shaded areas, benches and play areas for children, and is also home to the National Museum — a convenient stop for those exploring Malé''s cultural sites."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'sultan_park'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'sultan-park' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'sultan-park');
insert into node_media (node_id, media_id, role, sort_order) select id, '5d3bcf17-508b-e22c-459d-c51013949bc0', 'hero', 0 from nodes where node_type = 'location' and slug = 'sultan-park' on conflict (node_id, media_id, role) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'maldives-islamic-centre', 'Maldives Islamic Centre', 'A prominent Malé landmark topped by a large golden dome, home to the largest mosque in the Maldives.', 'published', 'Maldives Islamic Centre | Maldives Attractions | MTG', 'A prominent Malé landmark topped by a large golden dome, home to the largest mosque in the Maldives.', '{"attraction_type":"religious","best_for":"Learning about Islamic architecture and culture","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"The Maldives Islamic Centre is one of the most prominent landmarks in Malé. The centre is known for its large golden dome, which dominates the city''s skyline. The mosque inside is the largest in the Maldives and can accommodate over 5,000 worshippers. Visitors are welcome to explore the mosque outside of prayer times, providing an opportunity to learn about Islamic architecture and culture in the Maldives — the centre also hosts cultural events and exhibitions throughout the year."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'maldives_islamic_centre'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'maldives-islamic-centre' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'maldives-islamic-centre');
insert into node_media (node_id, media_id, role, sort_order) select id, '207a40a1-ada3-7891-fd9c-52a48caf5f2a', 'hero', 0 from nodes where node_type = 'location' and slug = 'maldives-islamic-centre' on conflict (node_id, media_id, role) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'artificial-beach-male', 'Artificial Beach', 'A popular man-made beach on the eastern side of Malé, used for swimming, water sports and community events.', 'published', 'Artificial Beach | Maldives Attractions | MTG', 'A popular man-made beach on the eastern side of Malé, used for swimming, water sports and community events.', '{"attraction_type":"beach","best_for":"Swimming, sunset views, and local community events","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"Artificial Beach is a man-made beach located on the eastern side of Malé. It''s a popular spot for locals and tourists alike, offering a place to swim, relax and enjoy the sunset, and is a hub for various water sports and beach activities. The beach often hosts community events, including music festivals, parades and carnivals — a great place to experience local culture and enjoy some leisure time by the sea."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'artificial_beach_male'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'artificial-beach-male' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'artificial-beach-male');
insert into node_media (node_id, media_id, role, sort_order) select id, '3678fc10-a6db-23d4-dceb-b59185c4a6b3', 'hero', 0 from nodes where node_type = 'location' and slug = 'artificial-beach-male' on conflict (node_id, media_id, role) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'victory-monument-male', 'Victory Monument', 'A Malé monument near Republic Square commemorating the government''s victory over a 1988 coup attempt.', 'published', 'Victory Monument | Maldives Attractions | MTG', 'A Malé monument near Republic Square commemorating the government''s victory over a 1988 coup attempt.', '{"attraction_type":"monument","best_for":"A quick stop on a Malé walking tour","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"The Victory Monument in Malé commemorates the victory of the Maldives government over a coup attempt in 1988. The monument is located near Republic Square and serves as a reminder of the country''s modern political history. It''s worth a quick visit for those interested in that history, and is located in a central area that''s easy to include in a walking tour of Malé."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'victory_monument_male'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'victory-monument-male' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'tsunami-monument-male', 'Tsunami Monument', 'A memorial on the southeastern side of Malé commemorating the lives lost in the 2004 Indian Ocean tsunami.', 'published', 'Tsunami Monument | Maldives Attractions | MTG', 'A memorial on the southeastern side of Malé commemorating the lives lost in the 2004 Indian Ocean tsunami.', '{"attraction_type":"monument","best_for":"A quiet, reflective stop with ocean views","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"The Tsunami Monument, located on the southeastern part of Malé, commemorates the lives lost in the 2004 Indian Ocean tsunami. The monument features a design with spheres representing the victims and steel rods symbolizing the impact of the waves. Visitors can reflect on the tragedy and resilience of the Maldivian people, with the surrounding area offering a peaceful environment with ocean views."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'tsunami_monument_male'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'tsunami-monument-male' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'tsunami-monument-male');
insert into node_media (node_id, media_id, role, sort_order) select id, 'ec16a513-b74d-675f-aa34-930f0ab7ec3d', 'hero', 0 from nodes where node_type = 'location' and slug = 'tsunami-monument-male' on conflict (node_id, media_id, role) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'male-fish-market', 'Malé Fish Market', 'A bustling working fish market in Malé where locals buy and sell the day''s catch, famous for feeding the resident stingrays.', 'published', 'Malé Fish Market | Maldives Attractions | MTG', 'A bustling working fish market in Malé where locals buy and sell the day''s catch, famous for feeding the resident stingrays.', '{"attraction_type":"market","best_for":"Experiencing everyday local life and culture","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"The Fish Market in Malé is a vibrant, bustling place where locals buy and sell fresh seafood — an excellent spot to witness the daily life of Malé''s residents and experience local food culture. Visitors can observe fishermen bringing in their catch of the day and even buy fresh fish to be cooked at nearby restaurants. The fishermen''s jetty in front of the market is where fish waste is discarded, a daily practice that draws stingrays which visitors can watch or feed."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'male_fish_market'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'male-fish-market' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'male-fish-market');
insert into node_media (node_id, media_id, role, sort_order) select id, '534b411e-fd78-091f-10b9-009abcc1a99a', 'hero', 0 from nodes where node_type = 'location' and slug = 'male-fish-market' on conflict (node_id, media_id, role) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'republic-square-male', 'Republic Square (Jumhooree Maidhaan)', 'Malé''s central public square, surrounded by government buildings and the site of national celebrations.', 'published', 'Republic Square (Jumhooree Maidhaan) | Maldives Attractions | MTG', 'Malé''s central public square, surrounded by government buildings and the site of national celebrations.', '{"attraction_type":"landmark","best_for":"Observing local culture and public events","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"Republic Square, also known as Jumhooree Maidhaan, is a central square in Malé that serves as a popular gathering place for locals. The square is surrounded by important government buildings, including the Presidential Palace and the headquarters of the Maldivian National Defence Force. It''s often the site of national celebrations, parades and other public events — a great place to observe local culture and the city''s atmosphere."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'republic_square_male'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'republic-square-male' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'republic-square-male');
insert into node_media (node_id, media_id, role, sort_order) select id, '1ca773b3-c63d-f6de-7dae-44552d2c7529', 'hero', 0 from nodes where node_type = 'location' and slug = 'republic-square-male' on conflict (node_id, media_id, role) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'sinamale-bridge', 'Sinamalé Bridge', 'The China-Maldives Friendship Bridge connecting Malé to Hulhulé Island and Velana International Airport.', 'published', 'Sinamalé Bridge | Maldives Attractions | MTG', 'The China-Maldives Friendship Bridge connecting Malé to Hulhulé Island and Velana International Airport.', '{"attraction_type":"infrastructure","best_for":"Sunset views and photography","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"The Sinamalé Bridge, also known as the China-Maldives Friendship Bridge, connects Malé with Hulhulé Island, where Velana International Airport is located. The bridge is a significant engineering achievement that has improved transportation between the islands. Visitors can walk or drive across it to enjoy panoramic views of the Indian Ocean and surrounding islands — it''s particularly beautiful at sunset, making it a popular photography spot."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'sinamale_bridge'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'sinamale-bridge' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'sinamale-bridge');
insert into node_media (node_id, media_id, role, sort_order) select id, '2d3c2642-7404-55fd-80a9-7e9a1d189dab', 'hero', 0 from nodes where node_type = 'location' and slug = 'sinamale-bridge' on conflict (node_id, media_id, role) do nothing;

insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, attributes, published_at) values ('location', 'rasfannu-beach', 'Rasfannu Beach', 'A small, popular urban beach on the western side of Malé, well known as a spot to watch the sunset.', 'published', 'Rasfannu Beach | Maldives Attractions | MTG', 'A small, popular urban beach on the western side of Malé, well known as a spot to watch the sunset.', '{"attraction_type":"beach","best_for":"Sunset views and a relaxed local beach atmosphere","source_article_slug":"beautiful-places-to-visit-in-maldives","body":"Rasfannu Beach is a small but popular urban beach located on the western side of Malé. The beach offers a convenient spot for swimming, sunbathing and relaxing, with facilities such as showers, changing rooms and food stalls nearby. It''s a great place to catch the sunset in Malé, well-maintained and with a laid-back atmosphere that makes it a favorite for both locals and tourists."}'::jsonb, now()) on conflict (node_type, slug) do nothing;
insert into locations (id, location_type, parent_id, path) select n.id, 'poi', p.id, (p_loc.path || 'rasfannu_beach'::ltree) from nodes n, nodes p join locations p_loc on p_loc.id = p.id where n.node_type = 'location' and n.slug = 'rasfannu-beach' and p.node_type = 'location' and p.slug = 'male' on conflict (id) do nothing;
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'location' and slug = 'rasfannu-beach');
insert into node_media (node_id, media_id, role, sort_order) select id, '1e638f32-b0ce-fd12-0f2f-566849e78011', 'hero', 0 from nodes where node_type = 'location' and slug = 'rasfannu-beach' on conflict (node_id, media_id, role) do nothing;

