-- Owner-uploaded activity photos (assets/uploads/activities/*/) for the
-- real Male Atoll excursions recovered from the legacy site: Full Day
-- Excursion, Vaavu Atoll Excursion, Stingray Snorkeling, Nurse Shark
-- Snorkeling, Sandbank and Snorkeling Excursion, Dolphin Excursion.
-- island-hopping/ photos are registered here but not yet attached to a
-- node — the Island Tour activity is pending owner confirmation.
-- GENERATED FILE, regenerate with:
--   node scripts/attach-activity-uploads.mjs --commit

insert into media_assets (id, media_type, storage_path, alt_text) values ('a90a6479-9f96-9d9f-db9d-6d6d24f65952', 'image', 'uploads/assets/uploads/activities/dolphin/maldives-lucky-dolphin-trip.webp', 'Maldives Lucky Dolphin Trip - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('b8faf7b9-1941-ea95-8b17-758ce375657c', 'image', 'uploads/assets/uploads/activities/dolphin/maldives-dolphin-excursion.webp', 'maldives dolphin excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('cd0a8647-cb3e-72da-e64f-876cf9902ef7', 'image', 'uploads/assets/uploads/activities/dolphin/maldives-dolphin-trip.webp', 'maldives dolphin trip - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('d528c70b-442f-3452-957c-3ee397953979', 'image', 'uploads/assets/uploads/activities/dolphin/male-atoll-dolphin-trip.webp', 'male atoll dolphin trip - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('4f5eeda2-2663-6a3f-2497-a9749f9a5d85', 'image', 'uploads/assets/uploads/activities/dolphin/male-atoll-excursion.webp', 'male atoll excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('db20933b-db38-7f4d-899f-5ac744e7f141', 'image', 'uploads/assets/uploads/activities/full-day/maldives-lucky-dolphin-trip.webp', 'Maldives Lucky Dolphin Trip - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('29972e7b-128a-cddd-130c-03c8a26a6229', 'image', 'uploads/assets/uploads/activities/full-day/maldives-snorkeling.webp', 'Maldives snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c4d0b60e-1d1e-4d53-417d-e14862bec071', 'image', 'uploads/assets/uploads/activities/full-day/nurse-shark-point-snorkeling.webp', 'Nurse Shark Point Snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('0316bad5-785e-cedd-b5cf-f12fb8cb05db', 'image', 'uploads/assets/uploads/activities/full-day/stingray-point-snorkeling.webp', 'Stingray Point Snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('1e9679b3-2a13-5e4b-c7ac-37966e6ebdf6', 'image', 'uploads/assets/uploads/activities/full-day/hushaan-fromtinyisles-7hb1svez04k-unsplash.webp', 'hushaan fromtinyisles 7hB1sVEZ04k unsplash - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c68ba906-6c92-5368-4c8f-a0ce89a38647', 'image', 'uploads/assets/uploads/activities/full-day/island-hopping-tour.webp', 'island hopping tour - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('19e18816-19e5-e1d4-55ec-c8c2361d3359', 'image', 'uploads/assets/uploads/activities/full-day/local-island-visit.webp', 'local island visit - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6c82f207-cb5c-0949-a2ca-42d281823799', 'image', 'uploads/assets/uploads/activities/full-day/maldives-dolphin-excursion.webp', 'maldives dolphin excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('351f4f37-9ef8-d4d5-04a3-0d505962258e', 'image', 'uploads/assets/uploads/activities/full-day/maldives-dolphin-trip.webp', 'maldives dolphin trip - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('d1b0a83f-8d60-59c8-1f6e-544b434ddd39', 'image', 'uploads/assets/uploads/activities/full-day/maldives-sandbank.webp', 'maldives sandbank - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6db6a623-07eb-a903-3fc4-6a8c7cb78e95', 'image', 'uploads/assets/uploads/activities/full-day/maldives-snorkleing-point.webp', 'maldives snorkleing point - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('bf8b516e-d106-888b-52b3-11cb0b1070c0', 'image', 'uploads/assets/uploads/activities/full-day/male-atoll-dolphin-trip.jpeg', 'male atoll dolphin trip - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('01024993-72e5-b716-23cf-31a35a6f3938', 'image', 'uploads/assets/uploads/activities/full-day/male-atoll-dolphin-trip.webp', 'male atoll dolphin trip - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('ecd745e3-b02a-28d3-c3ae-1bc08484ba56', 'image', 'uploads/assets/uploads/activities/full-day/male-atoll-excursion.webp', 'male atoll excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('99a356e1-3a60-393d-4729-fb4188c98d15', 'image', 'uploads/assets/uploads/activities/full-day/male-atoll-island-hopping-tour.webp', 'male atoll island hopping tour - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('ac4c275e-7846-07cb-2275-de57bb0546e7', 'image', 'uploads/assets/uploads/activities/full-day/male-atoll-sand-bank-trip.webp', 'male atoll sand bank trip - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a4855a69-d7f3-91bd-b668-233821d25b6d', 'image', 'uploads/assets/uploads/activities/full-day/male-atoll-sandbank.webp', 'male atoll sandbank - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('b451b9f6-9b44-e642-5a20-0939a760a3b8', 'image', 'uploads/assets/uploads/activities/full-day/male-atoll-snorkeling.webp', 'male atoll snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('ee7d9c98-6c4b-714e-8565-d6401f377802', 'image', 'uploads/assets/uploads/activities/full-day/male-atoll-turtle-snorkeling.webp', 'male atoll turtle snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('7d3aa51e-55bc-d5da-ca3a-0dc5e0e88014', 'image', 'uploads/assets/uploads/activities/full-day/sand-bank-excursion.webp', 'sand bank excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c5f2e254-40ca-b2f6-0a3b-8a22909ff286', 'image', 'uploads/assets/uploads/activities/full-day/sandbank-excursion-male-atoll.webp', 'sandbank excursion male atoll - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('eec2bbd1-bc7f-e11c-29f2-add04afd03a8', 'image', 'uploads/assets/uploads/activities/full-day/sandbank-excursion.webp', 'sandbank excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('4efb385b-6dd9-3275-81b6-8ecdcf365ff1', 'image', 'uploads/assets/uploads/activities/full-day/sandbank-maldives.webp', 'sandbank maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('7859900f-60e1-a05b-3447-1fe55292bccc', 'image', 'uploads/assets/uploads/activities/full-day/sandbank-visit-mael-atoll.webp', 'sandbank visit mael atoll - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('555cb82d-3aea-a8da-7801-0be168ef1344', 'image', 'uploads/assets/uploads/activities/full-day/snorkeling-activities-in-maldives.webp', 'snorkeling activities in maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('07f92260-a6c2-0c5a-df37-24d84a0b97fe', 'image', 'uploads/assets/uploads/activities/full-day/snorkeling-in-maldives.webp', 'snorkeling in maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('cf539589-c6bf-3a61-fa5a-6965dc8a9d0c', 'image', 'uploads/assets/uploads/activities/full-day/stingray-snorkeling-maldives.webp', 'stingray snorkeling maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('5bc5e8ac-1ccc-e140-c6e2-e65d400e4ad1', 'image', 'uploads/assets/uploads/activities/full-day/turtle-snorkeling-maldives.webp', 'turtle snorkeling maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('d37a3e46-f546-d07e-9d60-a5bee5fbc262', 'image', 'uploads/assets/uploads/activities/full-day/vaavu-nurse-shark-excursion.webp', 'vaavu nurse shark excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a8a47539-8cc2-c847-8f6b-3ead13f7e6f9', 'image', 'uploads/assets/uploads/activities/full-day/vaavu-shipwreck-excursion.webp', 'vaavu shipwreck excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('562993cb-02c3-2ced-01b9-e1fc1aef3b6f', 'image', 'uploads/assets/uploads/activities/full-day/vaavu-shipwreck-excursioon.webp', 'vaavu shipwreck excursioon - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c659adc5-ba2a-b971-13f8-ee23b29ed529', 'image', 'uploads/assets/uploads/activities/full-day/vaavu-shipwreck-snorkeling.webp', 'vaavu shipwreck snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('46953cfd-286c-4827-2e95-fd6c486d05c6', 'image', 'uploads/assets/uploads/activities/full-day/vaavu-shipwreck.webp', 'vaavu shipwreck - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c8488a67-4fc4-18ac-1916-063ec467d38e', 'image', 'uploads/assets/uploads/activities/full-day/visit-local-island-school.webp', 'visit local island school - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a2a714cf-a8e2-dd89-8a1a-9fceb6c578b2', 'image', 'uploads/assets/uploads/activities/full-day/visit-local-island-tour.webp', 'visit local island tour - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('7cb8da4d-bb3e-cda4-3da9-a3cc6a1801a1', 'image', 'uploads/assets/uploads/activities/nurse-shark/nurse-shark-point-snorkeling.jpeg', 'Nurse Shark Point Snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('65cbd30d-b2de-2c1f-c9c7-1442242be678', 'image', 'uploads/assets/uploads/activities/nurse-shark/nurse-shark-point-snorkeling.webp', 'Nurse Shark Point Snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('2432349b-609d-170f-215d-79575000aa25', 'image', 'uploads/assets/uploads/activities/nurse-shark/maldives-snorkeling.webp', 'maldives snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3b59eec2-b067-2219-1483-0cf609ec254c', 'image', 'uploads/assets/uploads/activities/nurse-shark/male-atoll-snorkeling.webp', 'male atoll snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('7b9cf078-a55b-da31-2c90-ffca456094b4', 'image', 'uploads/assets/uploads/activities/nurse-shark/nurs-shark-snorkeling.jpg', 'nurs shark snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6688dc2d-b55f-8537-d07d-12addff10ced', 'image', 'uploads/assets/uploads/activities/nurse-shark/nurs-shark-snorkeling.webp', 'nurs shark snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('25e02866-b8fc-e48a-ffd6-8fd096204ef8', 'image', 'uploads/assets/uploads/activities/nurse-shark/snorkeling-activity.jpg', 'snorkeling activity - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('2063c0d6-4061-839c-6c57-b62f543731e9', 'image', 'uploads/assets/uploads/activities/nurse-shark/snorkeling-activity.webp', 'snorkeling activity - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('b205a2d3-c95d-156c-1c3e-e961d7706127', 'image', 'uploads/assets/uploads/activities/nurse-shark/snorkeling-in-maldives.webp', 'snorkeling in maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('e4cc2faa-96a5-d364-7a87-b7e4a5cc4d81', 'image', 'uploads/assets/uploads/activities/nurse-shark/snorkeling-trip-to-nurs-shark.jpg', 'snorkeling trip to nurs shark - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a6f77b06-20f3-0c15-8900-35fb34e40143', 'image', 'uploads/assets/uploads/activities/nurse-shark/snorkeling-trip-to-nurs-shark.webp', 'snorkeling trip to nurs shark - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('7e0df579-f101-a86c-6b66-f51527442d98', 'image', 'uploads/assets/uploads/activities/nurse-shark/vaavu-nurse-shark-excursion.webp', 'vaavu nurse shark excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6f239b8d-847f-ddd7-2b4c-806f84ce6892', 'image', 'uploads/assets/uploads/activities/nurse-shark/vaavu-shipwreck-excursion.webp', 'vaavu shipwreck excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('876dc241-f551-ccf1-64cc-4e2a6d929f8d', 'image', 'uploads/assets/uploads/activities/nurse-shark/vaavu-shipwreck-excursioon.webp', 'vaavu shipwreck excursioon - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('100e8f5b-5f02-64cc-fa7b-fae8d07415eb', 'image', 'uploads/assets/uploads/activities/nurse-shark/vaavu-shipwreck-snorkeling.webp', 'vaavu shipwreck snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('36dd8227-b8f3-148b-772d-57c8f81a7732', 'image', 'uploads/assets/uploads/activities/nurse-shark/vaavu-shipwreck.jpeg', 'vaavu shipwreck - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('bf9f3393-7ad2-1ac9-5d65-928c155fefe9', 'image', 'uploads/assets/uploads/activities/nurse-shark/vaavu-shipwreck.webp', 'vaavu shipwreck - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f0546bd0-11a9-1175-4694-1cb8a7e35b83', 'image', 'uploads/assets/uploads/activities/sand-bank/maldives-sandbank.webp', 'maldives sandbank - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('d77b59a1-c4b8-b2ef-eadb-15db8eaf0680', 'image', 'uploads/assets/uploads/activities/sand-bank/male-atoll-sand-bank-trip.webp', 'male atoll sand bank trip - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('4b45d026-bd7d-15fa-a120-59bd75da3a89', 'image', 'uploads/assets/uploads/activities/sand-bank/male-atoll-sandbank.webp', 'male atoll sandbank - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('2ae7045d-29d0-6db4-6e68-15a37827265c', 'image', 'uploads/assets/uploads/activities/sand-bank/sand-bank-excursion.webp', 'sand bank excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('76ab04c6-e5ac-40f2-988b-66028bac5cee', 'image', 'uploads/assets/uploads/activities/sand-bank/sandbank-excursion-male-atoll.webp', 'sandbank excursion male atoll - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('361c27f2-bd8a-6aaf-1826-a845539ee57e', 'image', 'uploads/assets/uploads/activities/sand-bank/sandbank-excursion.webp', 'sandbank excursion - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3e241050-9687-ae0c-f4cb-268c6c4f9819', 'image', 'uploads/assets/uploads/activities/sand-bank/sandbank-maldives.jpeg', 'sandbank maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('e8bb6fde-2bd0-a178-a119-6f508c70bcc3', 'image', 'uploads/assets/uploads/activities/sand-bank/sandbank-maldives.webp', 'sandbank maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('eae978b6-8345-0714-7cc1-ab2cfe4bbac7', 'image', 'uploads/assets/uploads/activities/sand-bank/sandbank-trip.webp', 'sandbank trip - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('218713f9-f247-0d52-dfb0-29fd30157eb5', 'image', 'uploads/assets/uploads/activities/sand-bank/sandbank-visit-mael-atoll.webp', 'sandbank visit mael atoll - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('8b735221-0b19-647d-8747-b3a2ef0b846f', 'image', 'uploads/assets/uploads/activities/stingray/maldives-snorkeling.webp', 'Maldives snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('0d38ad5c-7fab-c0b0-990c-a1828a8b447a', 'image', 'uploads/assets/uploads/activities/stingray/stingray-point-snorkeling.jpeg', 'Stingray Point Snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('8fbf8e7f-a2da-3593-cbd0-f6e1b7e18dda', 'image', 'uploads/assets/uploads/activities/stingray/stingray-point-snorkeling.webp', 'Stingray Point Snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3654841d-39a8-85b2-4329-efda5c968352', 'image', 'uploads/assets/uploads/activities/stingray/maldives-snorkleing-point.webp', 'maldives snorkleing point - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('2924a90c-6230-436d-1366-05f194cd807f', 'image', 'uploads/assets/uploads/activities/stingray/male-atoll-turtle-snorkeling.webp', 'male atoll turtle snorkeling - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('9e423538-2739-16bb-1d11-2ad43567510d', 'image', 'uploads/assets/uploads/activities/stingray/snorkeling-activities-in-maldives.webp', 'snorkeling activities in maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3611dc34-4c4f-8a35-7f09-3d8d21aac232', 'image', 'uploads/assets/uploads/activities/stingray/stingray-snorkeling-maldives.webp', 'stingray snorkeling maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('1c46a23a-0809-d2a2-c705-a6b473820306', 'image', 'uploads/assets/uploads/activities/stingray/turtle-snorkeling-maldives.webp', 'turtle snorkeling maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3b67e938-259e-48aa-604e-24dab70ab899', 'image', 'uploads/assets/uploads/activities/island-hopping/things-to-do-in-maldives.webp', 'Things to do in maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('1d24de20-21f8-c291-83c4-6d970d50d1c7', 'image', 'uploads/assets/uploads/activities/island-hopping/fish-market-in-maldives.webp', 'fish market in maldives - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('dfa79407-4228-b4ac-d2fa-1eadc66f9bf6', 'image', 'uploads/assets/uploads/activities/island-hopping/fullday-activities-male-atoll.jpg', 'fullday activities male atoll - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a2e279e3-2c6e-9135-444c-e13d56aa07df', 'image', 'uploads/assets/uploads/activities/island-hopping/fullday-activities-male-atoll.webp', 'fullday activities male atoll - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a7a76bbf-5705-784c-01ea-84ce12128dcf', 'image', 'uploads/assets/uploads/activities/island-hopping/hushaan-fromtinyisles-7hb1svez04k-unsplash.webp', 'hushaan fromtinyisles 7hB1sVEZ04k unsplash - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('e4e16cdb-ff4a-1742-12f1-0db90d54f453', 'image', 'uploads/assets/uploads/activities/island-hopping/island-hopping-tour.jpg', 'island hopping tour - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('92388d6f-6543-a3cc-b60a-98efb37829c0', 'image', 'uploads/assets/uploads/activities/island-hopping/island-hopping-tour.webp', 'island hopping tour - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3862a41d-63c9-20c7-d247-8c4d98da045f', 'image', 'uploads/assets/uploads/activities/island-hopping/local-island-visit.jpg', 'local island visit - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c742c024-7507-22ea-a996-b6ae773b4174', 'image', 'uploads/assets/uploads/activities/island-hopping/local-island-visit.webp', 'local island visit - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('b4d1965d-c267-a8e0-3771-5c7e4878457a', 'image', 'uploads/assets/uploads/activities/island-hopping/male-atoll-island-hopping-tour.jpg', 'male atoll island hopping tour - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('5497fe83-2d61-fbb7-719d-f60d7cff092d', 'image', 'uploads/assets/uploads/activities/island-hopping/male-atoll-island-hopping-tour.webp', 'male atoll island hopping tour - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('9e562789-3b71-9e3b-cc30-bd8bc1d3f2d6', 'image', 'uploads/assets/uploads/activities/island-hopping/male-city-car-tour.webp', 'male city car tour - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('cd8b3f0a-4b95-8012-3de3-1a686e514e76', 'image', 'uploads/assets/uploads/activities/island-hopping/mtg.jpeg', 'mtg - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('243f4bce-b05b-0a77-604b-7a46e27537a0', 'image', 'uploads/assets/uploads/activities/island-hopping/visit-local-island-school.jpg', 'visit local island school - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('73f638f5-133c-0a50-ee18-ebfdc983c895', 'image', 'uploads/assets/uploads/activities/island-hopping/visit-local-island-school.webp', 'visit local island school - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('2c5e8ec3-4a24-3098-dfd9-52df6f71b60d', 'image', 'uploads/assets/uploads/activities/island-hopping/visit-local-island-tour.jpg', 'visit local island tour - Maldives activities') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('4c0edd3e-bb81-bcb8-d1f7-890a3a962f4c', 'image', 'uploads/assets/uploads/activities/island-hopping/visit-local-island-tour.webp', 'visit local island tour - Maldives activities') on conflict (id) do nothing;

-- Activity: full-day-excursion-male-atoll
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'full-day-excursion-male-atoll');
insert into node_media (node_id, media_id, role, sort_order) select id, '0316bad5-785e-cedd-b5cf-f12fb8cb05db', 'hero', 0 from nodes where node_type = 'activity' and slug = 'full-day-excursion-male-atoll' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'c4d0b60e-1d1e-4d53-417d-e14862bec071', 'gallery', 1 from nodes where node_type = 'activity' and slug = 'full-day-excursion-male-atoll' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'd1b0a83f-8d60-59c8-1f6e-544b434ddd39', 'gallery', 2 from nodes where node_type = 'activity' and slug = 'full-day-excursion-male-atoll' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'db20933b-db38-7f4d-899f-5ac744e7f141', 'gallery', 3 from nodes where node_type = 'activity' and slug = 'full-day-excursion-male-atoll' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '1e9679b3-2a13-5e4b-c7ac-37966e6ebdf6', 'gallery', 4 from nodes where node_type = 'activity' and slug = 'full-day-excursion-male-atoll' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'c68ba906-6c92-5368-4c8f-a0ce89a38647', 'gallery', 5 from nodes where node_type = 'activity' and slug = 'full-day-excursion-male-atoll' on conflict (node_id, media_id, role) do nothing;

-- Activity: nurse-shark-snorkeling
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'nurse-shark-snorkeling');
insert into node_media (node_id, media_id, role, sort_order) select id, '7b9cf078-a55b-da31-2c90-ffca456094b4', 'hero', 0 from nodes where node_type = 'activity' and slug = 'nurse-shark-snorkeling' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '6688dc2d-b55f-8537-d07d-12addff10ced', 'gallery', 1 from nodes where node_type = 'activity' and slug = 'nurse-shark-snorkeling' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '7cb8da4d-bb3e-cda4-3da9-a3cc6a1801a1', 'gallery', 2 from nodes where node_type = 'activity' and slug = 'nurse-shark-snorkeling' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '65cbd30d-b2de-2c1f-c9c7-1442242be678', 'gallery', 3 from nodes where node_type = 'activity' and slug = 'nurse-shark-snorkeling' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '2432349b-609d-170f-215d-79575000aa25', 'gallery', 4 from nodes where node_type = 'activity' and slug = 'nurse-shark-snorkeling' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3b59eec2-b067-2219-1483-0cf609ec254c', 'gallery', 5 from nodes where node_type = 'activity' and slug = 'nurse-shark-snorkeling' on conflict (node_id, media_id, role) do nothing;

-- Activity: sandbank-and-snorkeling-excursion
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'sandbank-and-snorkeling-excursion');
insert into node_media (node_id, media_id, role, sort_order) select id, 'f0546bd0-11a9-1175-4694-1cb8a7e35b83', 'hero', 0 from nodes where node_type = 'activity' and slug = 'sandbank-and-snorkeling-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'd77b59a1-c4b8-b2ef-eadb-15db8eaf0680', 'gallery', 1 from nodes where node_type = 'activity' and slug = 'sandbank-and-snorkeling-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '4b45d026-bd7d-15fa-a120-59bd75da3a89', 'gallery', 2 from nodes where node_type = 'activity' and slug = 'sandbank-and-snorkeling-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '2ae7045d-29d0-6db4-6e68-15a37827265c', 'gallery', 3 from nodes where node_type = 'activity' and slug = 'sandbank-and-snorkeling-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '76ab04c6-e5ac-40f2-988b-66028bac5cee', 'gallery', 4 from nodes where node_type = 'activity' and slug = 'sandbank-and-snorkeling-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '361c27f2-bd8a-6aaf-1826-a845539ee57e', 'gallery', 5 from nodes where node_type = 'activity' and slug = 'sandbank-and-snorkeling-excursion' on conflict (node_id, media_id, role) do nothing;

-- Activity: stingray-snorkeling
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'stingray-snorkeling');
insert into node_media (node_id, media_id, role, sort_order) select id, '0d38ad5c-7fab-c0b0-990c-a1828a8b447a', 'hero', 0 from nodes where node_type = 'activity' and slug = 'stingray-snorkeling' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8fbf8e7f-a2da-3593-cbd0-f6e1b7e18dda', 'gallery', 1 from nodes where node_type = 'activity' and slug = 'stingray-snorkeling' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8b735221-0b19-647d-8747-b3a2ef0b846f', 'gallery', 2 from nodes where node_type = 'activity' and slug = 'stingray-snorkeling' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3654841d-39a8-85b2-4329-efda5c968352', 'gallery', 3 from nodes where node_type = 'activity' and slug = 'stingray-snorkeling' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '2924a90c-6230-436d-1366-05f194cd807f', 'gallery', 4 from nodes where node_type = 'activity' and slug = 'stingray-snorkeling' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '9e423538-2739-16bb-1d11-2ad43567510d', 'gallery', 5 from nodes where node_type = 'activity' and slug = 'stingray-snorkeling' on conflict (node_id, media_id, role) do nothing;

-- Activity: dolphin-excursion
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'dolphin-excursion');
insert into node_media (node_id, media_id, role, sort_order) select id, 'a90a6479-9f96-9d9f-db9d-6d6d24f65952', 'hero', 0 from nodes where node_type = 'activity' and slug = 'dolphin-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'b8faf7b9-1941-ea95-8b17-758ce375657c', 'gallery', 1 from nodes where node_type = 'activity' and slug = 'dolphin-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'cd0a8647-cb3e-72da-e64f-876cf9902ef7', 'gallery', 2 from nodes where node_type = 'activity' and slug = 'dolphin-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'd528c70b-442f-3452-957c-3ee397953979', 'gallery', 3 from nodes where node_type = 'activity' and slug = 'dolphin-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '4f5eeda2-2663-6a3f-2497-a9749f9a5d85', 'gallery', 4 from nodes where node_type = 'activity' and slug = 'dolphin-excursion' on conflict (node_id, media_id, role) do nothing;

-- Activity: vaavu-atoll-excursion
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'vaavu-atoll-excursion');
insert into node_media (node_id, media_id, role, sort_order) select id, '6f239b8d-847f-ddd7-2b4c-806f84ce6892', 'hero', 0 from nodes where node_type = 'activity' and slug = 'vaavu-atoll-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '7e0df579-f101-a86c-6b66-f51527442d98', 'gallery', 1 from nodes where node_type = 'activity' and slug = 'vaavu-atoll-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '100e8f5b-5f02-64cc-fa7b-fae8d07415eb', 'gallery', 2 from nodes where node_type = 'activity' and slug = 'vaavu-atoll-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '876dc241-f551-ccf1-64cc-4e2a6d929f8d', 'gallery', 3 from nodes where node_type = 'activity' and slug = 'vaavu-atoll-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '36dd8227-b8f3-148b-772d-57c8f81a7732', 'gallery', 4 from nodes where node_type = 'activity' and slug = 'vaavu-atoll-excursion' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'bf9f3393-7ad2-1ac9-5d65-928c155fefe9', 'gallery', 5 from nodes where node_type = 'activity' and slug = 'vaavu-atoll-excursion' on conflict (node_id, media_id, role) do nothing;

