-- Round 2 of the owner's fishing gallery uploads (20 new files added to
-- assets/uploads/fishing/images/gallery/ after the first batch — see
-- scripts/attach-fishing-uploads.mjs for that original batch). Registers
-- one media_assets row per new file and appends them as additional
-- 'gallery' node_media rows on the real MFH lodge, continuing sort_order
-- from where the first batch left off. 4 of these files replace a
-- broken legacy fish-species photo reference (see fish-species.ts) —
-- those 4 are registered here for their media_assets row only; the
-- fish-species.ts code change itself is a separate, non-SQL edit.
-- GENERATED FILE, regenerate with:
--   node scripts/attach-fishing-gallery-round2.mjs --commit

insert into media_assets (id, media_type, storage_path, alt_text) values ('d21c225c-e40a-7361-63fa-3e072dd81026', 'image', 'uploads/assets/uploads/fishing/images/gallery/ari-atoll-spots.webp', 'ari atoll spots - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('095196ab-f287-c9a6-604f-6b6a0a9c5a83', 'image', 'uploads/assets/uploads/fishing/images/gallery/best-time-fishing.webp', 'best time fishing - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('2193250b-9c16-35ad-5cff-27dd8bee233d', 'image', 'uploads/assets/uploads/fishing/images/gallery/big-game-fishing-in-maldives.webp', 'big game fishing in maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6bf81059-4559-5a1b-0f5f-2a8dee9ca99b', 'image', 'uploads/assets/uploads/fishing/images/gallery/deep-sea-fishing-maldives.webp', 'deep sea fishing maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f7b6b8e0-4d72-6329-b52b-62c5f8b24472', 'image', 'uploads/assets/uploads/fishing/images/gallery/fishing-in-maldives.webp', 'fishing in maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('8dc28836-323e-85d9-d5ad-4d4ddd294c13', 'image', 'uploads/assets/uploads/fishing/images/gallery/fishing-tours-maldives.webp', 'fishing tours maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('9af0b52c-d5bf-c732-f0aa-cb9272c6e983', 'image', 'uploads/assets/uploads/fishing/images/gallery/fly-fishing-maldives.webp', 'fly fishing maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('65ce543b-f8cb-5760-a0ed-e49aefe7280d', 'image', 'uploads/assets/uploads/fishing/images/gallery/giant-yellowfin-tuna.webp', 'giant yellowfin tuna - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('63d606ab-e290-cc62-fe6e-b1fcf3bf5415', 'image', 'uploads/assets/uploads/fishing/images/gallery/gt-fishing-guide.webp', 'gt fishing guide - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('080f091e-1114-7565-3709-c85533388ec2', 'image', 'uploads/assets/uploads/fishing/images/gallery/mahi-mahi-fish.webp', 'mahi mahi fish - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('d82258a7-f7ae-f6ea-c603-5c18159eff68', 'image', 'uploads/assets/uploads/fishing/images/gallery/maldives-fishing-charters.webp', 'maldives fishing charters - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('0b224be8-cf15-e001-f9b4-7d32c3b664ea', 'image', 'uploads/assets/uploads/fishing/images/gallery/maldives-fishing-packages.webp', 'maldives fishing packages - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('437c760e-0079-e191-b056-ebe871a06643', 'image', 'uploads/assets/uploads/fishing/images/gallery/maldives-fishing-trips.webp', 'maldives fishing trips - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('720ed678-f61d-74c4-00d3-13879c709508', 'image', 'uploads/assets/uploads/fishing/images/gallery/maldives-fishing.webp', 'maldives fishing - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6a568121-cf94-c905-4b2d-bba7ceff1137', 'image', 'uploads/assets/uploads/fishing/images/gallery/redsnappers-in-maldives.webp', 'redsnappers in maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f561202d-6944-41a5-6bb8-7d414cbb0447', 'image', 'uploads/assets/uploads/fishing/images/gallery/sail-fishing-maldives.webp', 'sail fishing maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('7fb94bc0-e308-f850-82cf-10a86c0ee91d', 'image', 'uploads/assets/uploads/fishing/images/gallery/sports-fishing-maldives.webp', 'sports fishing maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('e5ffdf3e-f374-906a-92b3-61c4c7190d3c', 'image', 'uploads/assets/uploads/fishing/images/gallery/wahoo-in-maldives.webp', 'wahoo in maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('572c610a-06c9-2ce3-7a45-a3e102138d7c', 'image', 'uploads/assets/uploads/fishing/images/gallery/yellowfin-tuna.webp', 'yellowfin tuna - Maldives fishing') on conflict (id) do nothing;

-- Accommodation: maldives-fishing-and-holidays-lodge (append to existing gallery)
insert into node_media (node_id, media_id, role, sort_order) select id, 'd21c225c-e40a-7361-63fa-3e072dd81026', 'gallery', 11 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '095196ab-f287-c9a6-604f-6b6a0a9c5a83', 'gallery', 12 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '2193250b-9c16-35ad-5cff-27dd8bee233d', 'gallery', 13 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '6bf81059-4559-5a1b-0f5f-2a8dee9ca99b', 'gallery', 14 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f7b6b8e0-4d72-6329-b52b-62c5f8b24472', 'gallery', 15 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8dc28836-323e-85d9-d5ad-4d4ddd294c13', 'gallery', 16 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '9af0b52c-d5bf-c732-f0aa-cb9272c6e983', 'gallery', 17 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '65ce543b-f8cb-5760-a0ed-e49aefe7280d', 'gallery', 18 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '63d606ab-e290-cc62-fe6e-b1fcf3bf5415', 'gallery', 19 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '080f091e-1114-7565-3709-c85533388ec2', 'gallery', 20 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'd82258a7-f7ae-f6ea-c603-5c18159eff68', 'gallery', 21 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '0b224be8-cf15-e001-f9b4-7d32c3b664ea', 'gallery', 22 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '437c760e-0079-e191-b056-ebe871a06643', 'gallery', 23 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '720ed678-f61d-74c4-00d3-13879c709508', 'gallery', 24 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '6a568121-cf94-c905-4b2d-bba7ceff1137', 'gallery', 25 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f561202d-6944-41a5-6bb8-7d414cbb0447', 'gallery', 26 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '7fb94bc0-e308-f850-82cf-10a86c0ee91d', 'gallery', 27 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'e5ffdf3e-f374-906a-92b3-61c4c7190d3c', 'gallery', 28 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '572c610a-06c9-2ce3-7a45-a3e102138d7c', 'gallery', 29 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;

