-- Owner-uploaded fishing charter/gallery/package/lodge photos
-- (assets/uploads/fishing/images/ + assets/uploads/hotels/maldives-fishing/)
-- — real photos the owner pushed directly for the one real MFH
-- charter/lodge/package listing (confirmed via AskUserQuestion, not
-- separate businesses despite most charter filenames).
-- GENERATED FILE, regenerate with:
--   node scripts/attach-fishing-uploads.mjs --commit

insert into media_assets (id, media_type, storage_path, alt_text) values ('231eed3c-1bc0-71fb-4187-ca095c8d7630', 'image', 'uploads/assets/uploads/fishing/images/charters/emperor-fishing-boat.webp', 'emperor fishing boat - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('94bb6eed-690f-20c7-1169-f3c0b0a9466d', 'image', 'uploads/assets/uploads/fishing/images/charters/emperor-fishing-charter.webp', 'emperor fishing charter - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('e520e856-d8be-505a-1e39-bc1a61f726e0', 'image', 'uploads/assets/uploads/fishing/images/charters/emperor.webp', 'emperor - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('76017a89-829a-df0d-f1cc-fa3bd6721535', 'image', 'uploads/assets/uploads/fishing/images/charters/maldives-fishing-boat-charter.webp', 'maldives fishing boat charter - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('7e90fcd5-499f-8989-6783-c3ff27ee5bb1', 'image', 'uploads/assets/uploads/fishing/images/charters/maldives-fishing-boat-emperor.webp', 'maldives fishing boat emperor - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('e8bacc04-b06a-fbfc-da91-61c839832d4d', 'image', 'uploads/assets/uploads/fishing/images/charters/maldives-fishing-boat.webp', 'maldives fishing boat - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('2fa9be7f-a6f9-f278-4d61-54bcb4791558', 'image', 'uploads/assets/uploads/fishing/images/charters/maldives-fishing-charter.webp', 'maldives fishing charter - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('fdbbcf64-43d6-21f0-acde-dab3ea37d416', 'image', 'uploads/assets/uploads/fishing/images/charters/addu-adventurer.webp', 'addu adventurer - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('55c9edd5-5978-b431-8d74-3f85ee42790b', 'image', 'uploads/assets/uploads/fishing/images/charters/atoll-drifter-thaa.webp', 'atoll drifter thaa - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f30191e5-979d-29f9-c11a-f66b7cdd0121', 'image', 'uploads/assets/uploads/fishing/images/charters/blue-horizon-male.webp', 'blue horizon male - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('627b4792-501f-a1ce-0b40-1ddb3a0f6412', 'image', 'uploads/assets/uploads/fishing/images/charters/coral-queen-meemu.webp', 'coral queen meemu - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('354c0a53-0f07-6949-f6b8-61c929c169bb', 'image', 'uploads/assets/uploads/fishing/images/charters/deep-blue-noonu.webp', 'deep blue noonu - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('93aefb1a-b53a-f80c-48f9-ed69d5570306', 'image', 'uploads/assets/uploads/fishing/images/charters/dhoni-fisher-raa.webp', 'dhoni fisher raa - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a4348f77-376a-5b2d-57a0-e5c2c76ed0fd', 'image', 'uploads/assets/uploads/fishing/images/charters/equator-star-gaaf.webp', 'equator star gaaf - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('160ca86f-df5a-04b6-0c27-0bdc07407389', 'image', 'uploads/assets/uploads/fishing/images/charters/gt-slayer-male.webp', 'gt slayer male - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('bdd91e7b-8d1b-a98c-8e12-b50807ec0a53', 'image', 'uploads/assets/uploads/fishing/images/charters/island-spirit-ari.webp', 'island spirit ari - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('62cfa070-1a33-708b-6729-1a5cee5b6a49', 'image', 'uploads/assets/uploads/fishing/images/charters/laamu-legend.webp', 'laamu legend - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('5cc97704-17bd-e392-ce43-48387efd45e3', 'image', 'uploads/assets/uploads/fishing/images/charters/maldivian-dream-male.webp', 'maldivian dream male - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('022dd912-07a8-0b50-8d39-0da749f0ceeb', 'image', 'uploads/assets/uploads/fishing/images/charters/marlin-master-vaavu.avif', 'marlin master vaavu - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('ee81f8be-1730-65c7-5690-998845858464', 'image', 'uploads/assets/uploads/fishing/images/charters/ocean-hunter-ari.webp', 'ocean hunter ari - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('cc3f1d72-16ba-7cdc-86b6-3d90b15ed0df', 'image', 'uploads/assets/uploads/fishing/images/charters/reef-raider-baa.webp', 'reef raider baa - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('7c8dc296-ea28-64f1-8d8b-d1058387f304', 'image', 'uploads/assets/uploads/fishing/images/charters/southern-cross-dhaalu.webp', 'southern cross dhaalu - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('66b60873-da77-9174-d3ec-2412d7bf9d69', 'image', 'uploads/assets/uploads/fishing/images/charters/tuna-express-lhaviyani.webp', 'tuna express lhaviyani - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('cdb0fc20-985d-4734-a1c8-79b6d020e07a', 'image', 'uploads/assets/uploads/fishing/images/gallery/fishing-charter-boat.webp', 'Fishing charter boat - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('8c2e8baf-376e-b0b6-a222-a8450b073a09', 'image', 'uploads/assets/uploads/fishing/images/gallery/maldives-atoll-aerial-view.webp', 'Maldives atoll aerial view - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('dbd93db3-e064-94a9-5883-96ea6c3aebf1', 'image', 'uploads/assets/uploads/fishing/images/gallery/blue-marlin.avif', 'Blue marlin - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('cd447d34-97f4-718f-3b87-779345d99c1f', 'image', 'uploads/assets/uploads/fishing/images/gallery/fishing-liveaboard-maldives.webp', 'fishing liveaboard Maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c1e3ca08-0e43-1f98-3061-c6d9951c6834', 'image', 'uploads/assets/uploads/fishing/images/gallery/giant-trevally.webp', 'giant trevally - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a1f586e2-ef91-87af-5d6f-c1b39315a7d7', 'image', 'uploads/assets/uploads/fishing/images/gallery/reef-fishing-grouper.webp', 'Reef fishing grouper - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('d647a2a4-2099-8667-168f-88c292b6de0d', 'image', 'uploads/assets/uploads/fishing/images/gallery/sailfish-maldives.webp', 'Sailfish maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a8ba6833-886f-504b-136f-7cb31111c497', 'image', 'uploads/assets/uploads/fishing/images/gallery/yellowfin-tuna-fishing-maldives.webp', 'Yellowfin tuna fishing Maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('34d3a832-9c47-4608-4b21-3ab917b11418', 'image', 'uploads/assets/uploads/fishing/images/packages/big-game-fishing-in-maldives.webp', 'big game fishing in maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('468db768-64ec-c26a-3fb0-1e39e4862f27', 'image', 'uploads/assets/uploads/fishing/images/packages/bottom-meemu.webp', 'bottom meemu - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('5a298822-ac29-e70d-ab95-86e81ccc1977', 'image', 'uploads/assets/uploads/fishing/images/packages/deep-laamu.webp', 'deep laamu - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('d7cdb13d-0b83-4bca-fa8a-2ede82941941', 'image', 'uploads/assets/uploads/fishing/images/packages/explorer-gaaf.webp', 'explorer gaaf - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6438802c-801f-b2aa-a77d-af0e3c1df112', 'image', 'uploads/assets/uploads/fishing/images/packages/family-ari.webp', 'family ari - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('824e6e0b-16f8-2420-1d18-964d52647acf', 'image', 'uploads/assets/uploads/fishing/images/packages/fishing-tours-maldives.webp', 'fishing tours maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a36d4a5b-78ec-d507-256b-4aa72ce70a05', 'image', 'uploads/assets/uploads/fishing/images/packages/fly-addu.webp', 'fly addu - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f8056c21-0415-bd3a-bb0e-eae40c5c0a7e', 'image', 'uploads/assets/uploads/fishing/images/packages/grand-slam-ari.webp', 'grand slam ari - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6b7a8751-b720-7f64-f773-6ecf5e25287c', 'image', 'uploads/assets/uploads/fishing/images/packages/gt-safari-male.webp', 'gt safari male - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('0d2a1fac-1296-34d1-de17-05f73ce2228b', 'image', 'uploads/assets/uploads/fishing/images/packages/jigging-lhaviyani.webp', 'jigging lhaviyani - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('35f87a59-f0dc-f8d5-cf1f-dd2eeeee2203', 'image', 'uploads/assets/uploads/fishing/images/packages/luxury-dhaalu.webp', 'luxury dhaalu - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('870b3478-e43e-f532-e4b3-63a7001ca306', 'image', 'uploads/assets/uploads/fishing/images/packages/mahi-mahi-fish.webp', 'mahi mahi fish - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('7d531cad-b82a-e7e1-ecce-a68073a0959c', 'image', 'uploads/assets/uploads/fishing/images/packages/maldives-fishing.webp', 'maldives fishing - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('75c3a404-3596-d027-80ae-bff1528c8b8e', 'image', 'uploads/assets/uploads/fishing/images/packages/marlin-ari.webp', 'marlin ari - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c2cf94b2-8642-b77a-ea5e-2b0acaf84026', 'image', 'uploads/assets/uploads/fishing/images/packages/night-vaavu.webp', 'night vaavu - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('ead2e1da-00ff-1554-b001-6bdc3d5885fe', 'image', 'uploads/assets/uploads/fishing/images/packages/reef-baa.webp', 'reef baa - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('9dee044a-6c7e-7a4b-ebc5-3f1e13ec0ae4', 'image', 'uploads/assets/uploads/fishing/images/packages/sailfish-noonu.webp', 'sailfish noonu - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('bb2efb47-152b-60e9-2443-dacc2bd61f65', 'image', 'uploads/assets/uploads/fishing/images/packages/sunset-raa.webp', 'sunset raa - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('fdcb6dcb-87a4-1f21-4095-4e9ffc1be220', 'image', 'uploads/assets/uploads/fishing/images/packages/trolling-fishing.webp', 'trolling fishing - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('1505402c-5d03-9f97-3c2b-2a173a8f46e5', 'image', 'uploads/assets/uploads/fishing/images/packages/tuna-male.webp', 'tuna male - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('9faa8de9-cead-2c82-9035-6a94b5439343', 'image', 'uploads/assets/uploads/fishing/images/packages/wahoo-in-maldives.webp', 'wahoo in maldives - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('2e497ee9-3526-15e3-d731-92694cf8a8a7', 'image', 'uploads/assets/uploads/fishing/images/packages/wahoo-thaa.webp', 'wahoo thaa - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('4ff44b0e-81a3-a18f-cf0f-d781fccc47e6', 'image', 'uploads/assets/uploads/fishing/images/packages/yellowfin-tuna.webp', 'yellowfin tuna - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('4fae80b5-6160-e076-b924-5c1ca19c49a2', 'image', 'uploads/assets/uploads/hotels/maldives-fishing/maldives-fishing-and-holidays-lodge-guest-house.jpeg', 'Maldives fishing and holidays lodge guest house - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('1dba149e-3505-a13c-6d73-83d31921a490', 'image', 'uploads/assets/uploads/hotels/maldives-fishing/maldives-fishing-and-holidays-lodge-hotel.jpeg', 'Maldives fishing and holidays lodge hotel - Maldives fishing') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('234e95e6-158f-2fbc-9199-092435579450', 'image', 'uploads/assets/uploads/hotels/maldives-fishing/maldives-fishing-and-holidays-lodge.jpeg', 'Maldives fishing and holidays lodge - Maldives fishing') on conflict (id) do nothing;

-- Charter activity: private-full-day-fishing-charter
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter');
insert into node_media (node_id, media_id, role, sort_order) select id, '231eed3c-1bc0-71fb-4187-ca095c8d7630', 'hero', 0 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '94bb6eed-690f-20c7-1169-f3c0b0a9466d', 'gallery', 1 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'e520e856-d8be-505a-1e39-bc1a61f726e0', 'gallery', 2 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '76017a89-829a-df0d-f1cc-fa3bd6721535', 'gallery', 3 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '7e90fcd5-499f-8989-6783-c3ff27ee5bb1', 'gallery', 4 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'e8bacc04-b06a-fbfc-da91-61c839832d4d', 'gallery', 5 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '2fa9be7f-a6f9-f278-4d61-54bcb4791558', 'gallery', 6 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'fdbbcf64-43d6-21f0-acde-dab3ea37d416', 'gallery', 7 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '55c9edd5-5978-b431-8d74-3f85ee42790b', 'gallery', 8 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f30191e5-979d-29f9-c11a-f66b7cdd0121', 'gallery', 9 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '627b4792-501f-a1ce-0b40-1ddb3a0f6412', 'gallery', 10 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '354c0a53-0f07-6949-f6b8-61c929c169bb', 'gallery', 11 from nodes where node_type = 'activity' and slug = 'private-full-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;

-- Charter activity: private-half-day-fishing-charter
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter');
insert into node_media (node_id, media_id, role, sort_order) select id, '93aefb1a-b53a-f80c-48f9-ed69d5570306', 'hero', 0 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a4348f77-376a-5b2d-57a0-e5c2c76ed0fd', 'gallery', 1 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '160ca86f-df5a-04b6-0c27-0bdc07407389', 'gallery', 2 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'bdd91e7b-8d1b-a98c-8e12-b50807ec0a53', 'gallery', 3 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '62cfa070-1a33-708b-6729-1a5cee5b6a49', 'gallery', 4 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '5cc97704-17bd-e392-ce43-48387efd45e3', 'gallery', 5 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '022dd912-07a8-0b50-8d39-0da749f0ceeb', 'gallery', 6 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'ee81f8be-1730-65c7-5690-998845858464', 'gallery', 7 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'cc3f1d72-16ba-7cdc-86b6-3d90b15ed0df', 'gallery', 8 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '7c8dc296-ea28-64f1-8d8b-d1058387f304', 'gallery', 9 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '66b60873-da77-9174-d3ec-2412d7bf9d69', 'gallery', 10 from nodes where node_type = 'activity' and slug = 'private-half-day-fishing-charter' on conflict (node_id, media_id, role) do nothing;

-- Accommodation: maldives-fishing-and-holidays-lodge
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge');
insert into node_media (node_id, media_id, role, sort_order) select id, '4fae80b5-6160-e076-b924-5c1ca19c49a2', 'hero', 0 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '1dba149e-3505-a13c-6d73-83d31921a490', 'gallery', 1 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '234e95e6-158f-2fbc-9199-092435579450', 'gallery', 2 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'cdb0fc20-985d-4734-a1c8-79b6d020e07a', 'gallery', 3 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8c2e8baf-376e-b0b6-a222-a8450b073a09', 'gallery', 4 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'dbd93db3-e064-94a9-5883-96ea6c3aebf1', 'gallery', 5 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'cd447d34-97f4-718f-3b87-779345d99c1f', 'gallery', 6 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'c1e3ca08-0e43-1f98-3061-c6d9951c6834', 'gallery', 7 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a1f586e2-ef91-87af-5d6f-c1b39315a7d7', 'gallery', 8 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'd647a2a4-2099-8667-168f-88c292b6de0d', 'gallery', 9 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a8ba6833-886f-504b-136f-7cb31111c497', 'gallery', 10 from nodes where node_type = 'accommodation' and slug = 'maldives-fishing-and-holidays-lodge' on conflict (node_id, media_id, role) do nothing;

