-- Round 3 owner-uploaded photos (assets/uploads/{north,south}/) matched
-- to real entities that were still missing a hero image after round 2
-- (data/maldives/media/round2-still-missing-images.json).
-- GENERATED FILE, regenerate with:
--   node scripts/attach-round3-uploads.mjs --commit

-- Islands
insert into media_assets (id, media_type, storage_path, alt_text) values ('c78afd64-0754-f227-5821-80b9bf57431b', 'image', 'uploads/assets/uploads/north/alifu-alifu-feridhoo-island.webp', 'Alifu alifu Feridhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'c78afd64-0754-f227-5821-80b9bf57431b', 'hero', 0 from nodes where node_type = 'location' and slug = 'feridhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('fa61f5f3-8225-ef73-0141-e364d0217d11', 'image', 'uploads/assets/uploads/north/alifu-alifu-maalhos-island.jpg', 'Alifu alifu Maalhos island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'fa61f5f3-8225-ef73-0141-e364d0217d11', 'hero', 0 from nodes where node_type = 'location' and slug = 'maalhos-alif-alif' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('b766c663-ab9a-837e-ff21-ccc183a045c1', 'image', 'uploads/assets/uploads/north/alifu-alifu-mathiveri-island.jpg', 'Alifu alifu Mathiveri island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'b766c663-ab9a-837e-ff21-ccc183a045c1', 'hero', 0 from nodes where node_type = 'location' and slug = 'mathiveri' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f80530e1-5ea7-2263-0b4f-210176f608fc', 'image', 'uploads/assets/uploads/north/alifu-alifu-rasdhoo-island.jpg', 'Alifu alifu Rasdhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f80530e1-5ea7-2263-0b4f-210176f608fc', 'hero', 0 from nodes where node_type = 'location' and slug = 'rasdhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('0ec326ac-0e0c-b1ee-a6ff-1f9888c7cd2f', 'image', 'uploads/assets/uploads/north/alifu-dhaalu-dhangethi-isand.jpg', 'alifu dhaalu Dhangethi isand') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '0ec326ac-0e0c-b1ee-a6ff-1f9888c7cd2f', 'hero', 0 from nodes where node_type = 'location' and slug = 'dhangethi' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a6093e5b-18b5-9868-3150-e48dc6524649', 'image', 'uploads/assets/uploads/north/alifu-dhaalu-dhidhdhoo-isand.jpg', 'alifu dhaalu Dhidhdhoo isand') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a6093e5b-18b5-9868-3150-e48dc6524649', 'hero', 0 from nodes where node_type = 'location' and slug = 'dhidhdhoo-alif-dhaalu' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('1bd146e8-7c5d-0e6f-d0a7-1c269abf0e4e', 'image', 'uploads/assets/uploads/north/alifu-dhaalu-fenfushi-isand.jpg', 'alifu dhaalu Fenfushi isand') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '1bd146e8-7c5d-0e6f-d0a7-1c269abf0e4e', 'hero', 0 from nodes where node_type = 'location' and slug = 'fenfushi' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a8d3f342-840e-df4e-e024-1639023f56e0', 'image', 'uploads/assets/uploads/north/alifu-dhaalu-hangnaameedhoo-isand.jpg', 'alifu dhaalu Hangnaameedhoo isand') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a8d3f342-840e-df4e-e024-1639023f56e0', 'hero', 0 from nodes where node_type = 'location' and slug = 'hangnaameedhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('02b77aa1-c95f-c341-339c-f1912e11c087', 'image', 'uploads/assets/uploads/north/alifu-dhaalu-kunburudhoo-isand.jpg', 'alifu dhaalu Kunburudhoo isand') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '02b77aa1-c95f-c341-339c-f1912e11c087', 'hero', 0 from nodes where node_type = 'location' and slug = 'kunburudhoo-alif-dhaalu' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c77d9f6d-63de-0b3d-6acf-82cca18a463e', 'image', 'uploads/assets/uploads/north/alifu-dhaalu-mahibadhoo-isand.jpg', 'alifu dhaalu Mahibadhoo isand') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'c77d9f6d-63de-0b3d-6acf-82cca18a463e', 'hero', 0 from nodes where node_type = 'location' and slug = 'mahibadhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('ebf6c570-6efa-7897-0d11-ec1259c97949', 'image', 'uploads/assets/uploads/north/alifu-dhaalu-mandhoo-isand.jpg', 'alifu dhaalu Mandhoo isand') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'ebf6c570-6efa-7897-0d11-ec1259c97949', 'hero', 0 from nodes where node_type = 'location' and slug = 'mandhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3f039013-d33a-7639-3056-6e3525779098', 'image', 'uploads/assets/uploads/north/alifu-dhaalu-omadhoo-isand.jpg', 'alifu dhaalu Omadhoo isand') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3f039013-d33a-7639-3056-6e3525779098', 'hero', 0 from nodes where node_type = 'location' and slug = 'omadhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('086906f2-bcd2-3cef-72cd-a0bb6f0c2817', 'image', 'uploads/assets/uploads/north/ba-dhonfanu-island.jpg', 'ba Dhonfanu island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '086906f2-bcd2-3cef-72cd-a0bb6f0c2817', 'hero', 0 from nodes where node_type = 'location' and slug = 'dhonfanu' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('10ea3447-61c8-5788-0266-2e155b76f483', 'image', 'uploads/assets/uploads/north/ba-eydhafushi-island.jpg', 'ba Eydhafushi island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '10ea3447-61c8-5788-0266-2e155b76f483', 'hero', 0 from nodes where node_type = 'location' and slug = 'eydhafushi' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f535b66d-806a-843b-14eb-cfd35636896b', 'image', 'uploads/assets/uploads/north/ba-fehendhoo-island.jpg', 'ba Fehendhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f535b66d-806a-843b-14eb-cfd35636896b', 'hero', 0 from nodes where node_type = 'location' and slug = 'fehendhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6e17ff7a-3b06-7883-e0f6-73910a8f0e9a', 'image', 'uploads/assets/uploads/north/ba-fulhadhoo-island.jpg', 'ba Fulhadhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '6e17ff7a-3b06-7883-e0f6-73910a8f0e9a', 'hero', 0 from nodes where node_type = 'location' and slug = 'fulhadhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f5faa390-a477-7b25-ba67-1a54a9d2f825', 'image', 'uploads/assets/uploads/north/ba-hithaadhoo-island.jpg', 'ba Hithaadhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f5faa390-a477-7b25-ba67-1a54a9d2f825', 'hero', 0 from nodes where node_type = 'location' and slug = 'hithaadhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f1c10580-026d-99f0-cea5-fbccbd43d1c7', 'image', 'uploads/assets/uploads/north/ba-kamadhoo-island.jpg', 'ba Kamadhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f1c10580-026d-99f0-cea5-fbccbd43d1c7', 'hero', 0 from nodes where node_type = 'location' and slug = 'kamadhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('24d789b7-59c8-980e-12a8-82f99c1a7cca', 'image', 'uploads/assets/uploads/north/ba-kendhoo-island.jpg', 'ba Kendhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '24d789b7-59c8-980e-12a8-82f99c1a7cca', 'hero', 0 from nodes where node_type = 'location' and slug = 'kendhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('bfe6c192-ade8-df9d-a13a-9218cf74fdbe', 'image', 'uploads/assets/uploads/north/ba-kihaadhoo-island.jpg', 'ba Kihaadhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'bfe6c192-ade8-df9d-a13a-9218cf74fdbe', 'hero', 0 from nodes where node_type = 'location' and slug = 'kihaadhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('30485f4f-7a87-e7a8-0693-396b7a4ecb6a', 'image', 'uploads/assets/uploads/north/ba-kudarikilu-island.jpg', 'ba Kudarikilu island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '30485f4f-7a87-e7a8-0693-396b7a4ecb6a', 'hero', 0 from nodes where node_type = 'location' and slug = 'kudarikilu' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('182e704c-9ebe-bd9d-3b44-0547773a75f2', 'image', 'uploads/assets/uploads/north/ba-maalhos-island.jpg', 'ba Maalhos island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '182e704c-9ebe-bd9d-3b44-0547773a75f2', 'hero', 0 from nodes where node_type = 'location' and slug = 'maalhos' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('9957b1d7-d3e8-ff46-8947-497fa163236e', 'image', 'uploads/assets/uploads/north/ba-thulhaadhoo-island.jpg', 'ba Thulhaadhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '9957b1d7-d3e8-ff46-8947-497fa163236e', 'hero', 0 from nodes where node_type = 'location' and slug = 'thulhaadhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('9758e70c-0b0f-0382-e845-6274f349db8b', 'image', 'uploads/assets/uploads/north/ba-goidhoo-island.jpg', 'ba goidhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '9758e70c-0b0f-0382-e845-6274f349db8b', 'hero', 0 from nodes where node_type = 'location' and slug = 'goidhoo-baa' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('33ea123f-a2db-59ea-bebe-b6f4b5703aeb', 'image', 'uploads/assets/uploads/north/dhaalu-bandidhoo-maldives.jpg', 'dhaalu Bandidhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '33ea123f-a2db-59ea-bebe-b6f4b5703aeb', 'hero', 0 from nodes where node_type = 'location' and slug = 'bandidhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('4de57df2-2922-ec91-1b90-2eee3fa24e5e', 'image', 'uploads/assets/uploads/north/dhaalu-hulhudheli-maldives.jpg', 'dhaalu Hulhudheli maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '4de57df2-2922-ec91-1b90-2eee3fa24e5e', 'hero', 0 from nodes where node_type = 'location' and slug = 'hulhudheli' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3a4372fd-ec7c-d29a-3077-162e2296642c', 'image', 'uploads/assets/uploads/north/dhaalu-kudahuvadhoo-maldives.jpg', 'dhaalu Kudahuvadhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3a4372fd-ec7c-d29a-3077-162e2296642c', 'hero', 0 from nodes where node_type = 'location' and slug = 'kudahuvadhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f69a815c-994e-093b-71e2-160d4467906d', 'image', 'uploads/assets/uploads/north/dhaalu-maaenboodhoo-maldives.jpg', 'dhaalu Maaenboodhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f69a815c-994e-093b-71e2-160d4467906d', 'hero', 0 from nodes where node_type = 'location' and slug = 'maaenboodhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('eaf3a851-454d-27f5-369f-a45e9101fcc7', 'image', 'uploads/assets/uploads/north/dhaalu-meedhoo-maldives.jpg', 'dhaalu Meedhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'eaf3a851-454d-27f5-369f-a45e9101fcc7', 'hero', 0 from nodes where node_type = 'location' and slug = 'meedhoo-dhaalu' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('25c151c6-bc36-3041-7e40-ab51ad043c8e', 'image', 'uploads/assets/uploads/north/dhaalu-rinbudhoo-maldives.jpg', 'dhaalu Rinbudhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '25c151c6-bc36-3041-7e40-ab51ad043c8e', 'hero', 0 from nodes where node_type = 'location' and slug = 'rinbudhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('18ced427-2e55-af75-6ac2-136aa0505924', 'image', 'uploads/assets/uploads/north/faafu-dharanboodhoo-maldives.jpg', 'faafu Dharanboodhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '18ced427-2e55-af75-6ac2-136aa0505924', 'hero', 0 from nodes where node_type = 'location' and slug = 'dharanboodhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('8009c59a-0bd4-c07d-c639-cb1c60507183', 'image', 'uploads/assets/uploads/north/faafu-magoodhoo-maldives.jpg', 'faafu Magoodhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8009c59a-0bd4-c07d-c639-cb1c60507183', 'hero', 0 from nodes where node_type = 'location' and slug = 'magoodhoo-faafu' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('34f4ed70-d2ae-ea0b-dedc-125eee65ff05', 'image', 'uploads/assets/uploads/north/faafu-nilandhoo-maldives.jpg', 'faafu Nilandhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '34f4ed70-d2ae-ea0b-dedc-125eee65ff05', 'hero', 0 from nodes where node_type = 'location' and slug = 'nilandhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('4d5987c6-809d-5196-3123-b2f2bba8fba5', 'image', 'uploads/assets/uploads/north/faafu-feeali-maldives.jpg', 'faafu feeali maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '4d5987c6-809d-5196-3123-b2f2bba8fba5', 'hero', 0 from nodes where node_type = 'location' and slug = 'feeali' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('69404ae7-06f9-b7a5-27e8-2596eabde7d0', 'image', 'uploads/assets/uploads/south/hdh-nellaidhoo-island.jpg', 'hdh nellaidhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '69404ae7-06f9-b7a5-27e8-2596eabde7d0', 'hero', 0 from nodes where node_type = 'location' and slug = 'nellaidhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('ef7d7fb2-dee2-288c-9631-86386f04da82', 'image', 'uploads/assets/uploads/south/hdh-neykurendhoo-island.jpg', 'hdh neykurendhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'ef7d7fb2-dee2-288c-9631-86386f04da82', 'hero', 0 from nodes where node_type = 'location' and slug = 'neykurendhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('04b7eacc-e890-5841-dc12-b33b041cf1ad', 'image', 'uploads/assets/uploads/south/hdh-nolhivaram-island.jpg', 'hdh nolhivaram island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '04b7eacc-e890-5841-dc12-b33b041cf1ad', 'hero', 0 from nodes where node_type = 'location' and slug = 'nolhivaram' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('e4d916f0-4e94-bfc9-b9bd-9afbf57f761f', 'image', 'uploads/assets/uploads/south/hdh-nolhivaranfaru-island.jpg', 'hdh nolhivaranfaru island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'e4d916f0-4e94-bfc9-b9bd-9afbf57f761f', 'hero', 0 from nodes where node_type = 'location' and slug = 'nolhivaranfaru' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3f621d75-3eec-ec51-73f0-4f9581aec385', 'image', 'uploads/assets/uploads/south/hdh-vaikaradhoo-island.jpg', 'hdh vaikaradhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '3f621d75-3eec-ec51-73f0-4f9581aec385', 'hero', 0 from nodes where node_type = 'location' and slug = 'vaikaradhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6b7170de-af26-f948-8a81-21bfc4f45bd5', 'image', 'uploads/assets/uploads/south/kaafu-dhiffushi-island.jpg', 'kaafu Dhiffushi island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '6b7170de-af26-f948-8a81-21bfc4f45bd5', 'hero', 0 from nodes where node_type = 'location' and slug = 'dhiffushi' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('5c45fed3-c832-122f-0d3b-94c85d34ef42', 'image', 'uploads/assets/uploads/south/kaafu-guraidhoo-island.jpg', 'kaafu Guraidhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '5c45fed3-c832-122f-0d3b-94c85d34ef42', 'hero', 0 from nodes where node_type = 'location' and slug = 'guraidhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('4c149f1b-1b85-20b1-8670-5775f740b700', 'image', 'uploads/assets/uploads/south/kaafu-himmafushi-island.jpg', 'kaafu Himmafushi island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '4c149f1b-1b85-20b1-8670-5775f740b700', 'hero', 0 from nodes where node_type = 'location' and slug = 'himmafushi' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('cdef71c0-3e2b-b5be-e55d-f94f0f4ac889', 'image', 'uploads/assets/uploads/south/kaafu-kaashidhoo-island.jpg', 'kaafu Kaashidhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'cdef71c0-3e2b-b5be-e55d-f94f0f4ac889', 'hero', 0 from nodes where node_type = 'location' and slug = 'kaashidhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('e2e41f37-8a43-a8bf-1429-1bd3c2ba5ee5', 'image', 'uploads/assets/uploads/south/kaafu-gaafaru-island.jpg', 'kaafu gaafaru island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'e2e41f37-8a43-a8bf-1429-1bd3c2ba5ee5', 'hero', 0 from nodes where node_type = 'location' and slug = 'gaafaru' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('eff6ca8d-61f2-89a3-9e7a-01ba5add478c', 'image', 'uploads/assets/uploads/south/kaafu-gulhi-island.jpg', 'kaafu gulhi island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'eff6ca8d-61f2-89a3-9e7a-01ba5add478c', 'hero', 0 from nodes where node_type = 'location' and slug = 'gulhi' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('8d130521-7604-635f-3983-7589d299b8a9', 'image', 'uploads/assets/uploads/south/laamu-dhanbidhoo-maldives.jpg', 'laamu Dhanbidhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8d130521-7604-635f-3983-7589d299b8a9', 'hero', 0 from nodes where node_type = 'location' and slug = 'dhanbidhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('394ab67f-525e-fbc1-5aea-b44b8075cefd', 'image', 'uploads/assets/uploads/south/laamu-fonadhoo-maldives.jpg', 'laamu Fonadhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '394ab67f-525e-fbc1-5aea-b44b8075cefd', 'hero', 0 from nodes where node_type = 'location' and slug = 'fonadhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a061ca02-58e5-75f5-0ee0-dafb46b8f3d5', 'image', 'uploads/assets/uploads/south/laamu-hithadhoo-maldives.jpg', 'laamu Hithadhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a061ca02-58e5-75f5-0ee0-dafb46b8f3d5', 'hero', 0 from nodes where node_type = 'location' and slug = 'hithadhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a149683f-8b30-5ef2-6f5a-ef76d1b63c0e', 'image', 'uploads/assets/uploads/south/laamu-isdhoo-kalaidhoo-maldives.jpg', 'laamu Isdhoo kalaidhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a149683f-8b30-5ef2-6f5a-ef76d1b63c0e', 'hero', 0 from nodes where node_type = 'location' and slug = 'isdhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('90b1e2e0-93a8-60c7-836a-3483f0ffe126', 'image', 'uploads/assets/uploads/south/laamu-kunahandhoo-maldives.jpg', 'laamu Kunahandhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '90b1e2e0-93a8-60c7-836a-3483f0ffe126', 'hero', 0 from nodes where node_type = 'location' and slug = 'kunahandhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('729f5ed0-fb41-e6ec-d1dd-e943ef9282bc', 'image', 'uploads/assets/uploads/south/laamu-maabaidhoo-maldives.jpg', 'laamu Maabaidhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '729f5ed0-fb41-e6ec-d1dd-e943ef9282bc', 'hero', 0 from nodes where node_type = 'location' and slug = 'maabaidhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a43e8420-0b60-0951-b4a9-e8a641438017', 'image', 'uploads/assets/uploads/south/laamu-maamendhoo-maldives.jpg', 'laamu Maamendhoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a43e8420-0b60-0951-b4a9-e8a641438017', 'hero', 0 from nodes where node_type = 'location' and slug = 'maamendhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f4ad9cb5-bc78-2d59-aa0e-4a8275506f48', 'image', 'uploads/assets/uploads/south/laamu-maavah-maldives.jpg', 'laamu Maavah maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f4ad9cb5-bc78-2d59-aa0e-4a8275506f48', 'hero', 0 from nodes where node_type = 'location' and slug = 'maavah' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('d00bd44f-aada-1cec-2a30-1e285deb95bb', 'image', 'uploads/assets/uploads/south/laamu-mundoo-maldives.jpg', 'laamu Mundoo maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'd00bd44f-aada-1cec-2a30-1e285deb95bb', 'hero', 0 from nodes where node_type = 'location' and slug = 'mundoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('6762b92e-16d9-ca97-beb6-521876d5b947', 'image', 'uploads/assets/uploads/south/laamu-gan-maldives.jpg', 'laamu gan maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '6762b92e-16d9-ca97-beb6-521876d5b947', 'hero', 0 from nodes where node_type = 'location' and slug = 'gan' on conflict (node_id, media_id, role) do nothing;

-- Atolls
insert into media_assets (id, media_type, storage_path, alt_text) values ('f2178eff-d28d-d42a-8bae-d07ae66e1594', 'image', 'uploads/assets/uploads/north/dhaalu-atoll-maldives.jpg', 'dhaalu atoll maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f2178eff-d28d-d42a-8bae-d07ae66e1594', 'hero', 0 from nodes where node_type = 'location' and slug = 'dhaalu' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('7288bc17-b1f1-4ca0-ef6f-62dcefbd801d', 'image', 'uploads/assets/uploads/north/faafu-atoll-maldives.jpg', 'faafu atoll maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '7288bc17-b1f1-4ca0-ef6f-62dcefbd801d', 'hero', 0 from nodes where node_type = 'location' and slug = 'faafu' on conflict (node_id, media_id, role) do nothing;

-- Accommodations

-- Surf breaks

-- Articles

-- Attractions

-- Gallery-only extras for already-covered entities
insert into media_assets (id, media_type, storage_path, alt_text) values ('e78042e9-42e0-7408-1806-b6739f84feb3', 'image', 'uploads/assets/uploads/north/alifu-alifu-thoddoo-island.jpg', 'Alifu alifu Thoddoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'e78042e9-42e0-7408-1806-b6739f84feb3', 'gallery', 1 from nodes where node_type = 'location' and slug = 'thoddoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('f6ba51a5-2f0b-0e4c-2060-7e174d7ead65', 'image', 'uploads/assets/uploads/north/alifu-alifu-ukulhas-island.jpg', 'Alifu alifu Ukulhas island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'f6ba51a5-2f0b-0e4c-2060-7e174d7ead65', 'gallery', 1 from nodes where node_type = 'location' and slug = 'ukulhas' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('418dd439-9083-98be-4409-88c455c0b382', 'image', 'uploads/assets/uploads/north/alifu-dhaalu-dhigurah-isand.jpg', 'alifu dhaalu Dhigurah isand') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '418dd439-9083-98be-4409-88c455c0b382', 'gallery', 1 from nodes where node_type = 'location' and slug = 'dhigurah' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('1cb76419-5ba5-313c-9115-3bb44a2db721', 'image', 'uploads/assets/uploads/north/alifu-dhaalu-atoll-maldives.jpg', 'alifu dhaalu atoll maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '1cb76419-5ba5-313c-9115-3bb44a2db721', 'gallery', 1 from nodes where node_type = 'location' and slug = 'alif-dhaalu' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('e3acbcec-bead-29f6-85a5-909a6331a38d', 'image', 'uploads/assets/uploads/north/ba-dharavandhoo-island.jpg', 'ba Dharavandhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'e3acbcec-bead-29f6-85a5-909a6331a38d', 'gallery', 1 from nodes where node_type = 'location' and slug = 'dharavandhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a855c469-2ecc-39c6-fff6-710eddc9c4c2', 'image', 'uploads/assets/uploads/north/ba-atoll-maldives.jpg', 'ba atoll maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a855c469-2ecc-39c6-fff6-710eddc9c4c2', 'gallery', 1 from nodes where node_type = 'location' and slug = 'baa' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('80783c73-5126-1261-bc7c-536a88ccaf0c', 'image', 'uploads/assets/uploads/north/baa-atoll-map.webp', 'baa atoll map') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '80783c73-5126-1261-bc7c-536a88ccaf0c', 'gallery', 2 from nodes where node_type = 'location' and slug = 'baa' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('49e64491-0859-3789-22d4-e3c9b9c942b5', 'image', 'uploads/assets/uploads/south/kaafu-huraa-island.jpg', 'kaafu Huraa island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '49e64491-0859-3789-22d4-e3c9b9c942b5', 'gallery', 1 from nodes where node_type = 'location' and slug = 'huraa' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('da057f9b-56c1-e67f-a78a-c31a07a0f69c', 'image', 'uploads/assets/uploads/south/kaafu-maafushi-island.jpg', 'kaafu Maafushi island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'da057f9b-56c1-e67f-a78a-c31a07a0f69c', 'gallery', 1 from nodes where node_type = 'location' and slug = 'maafushi' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('ab6ea07c-881c-9d9d-9744-59bfe3d164d5', 'image', 'uploads/assets/uploads/south/kaafu-thulusdhoo-island.jpg', 'kaafu Thulusdhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'ab6ea07c-881c-9d9d-9744-59bfe3d164d5', 'gallery', 1 from nodes where node_type = 'location' and slug = 'thulusdhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('130ead9e-5750-c2b1-6f5e-141efb186318', 'image', 'uploads/assets/uploads/south/kaafu-atoll-maldives.jpg', 'kaafu atoll maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '130ead9e-5750-c2b1-6f5e-141efb186318', 'gallery', 1 from nodes where node_type = 'location' and slug = 'kaafu' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('dbdf5ec3-815e-3aa9-612d-2a625c03c0b6', 'image', 'uploads/assets/uploads/south/laamu-atoll-maldives.jpg', 'laamu atoll maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'dbdf5ec3-815e-3aa9-612d-2a625c03c0b6', 'gallery', 1 from nodes where node_type = 'location' and slug = 'laamu' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('be632e70-63b0-8ca7-270c-9504e052f4c6', 'image', 'uploads/assets/uploads/south/lhaviyani-hinnavaru-island.jpg', 'lhaviyani Hinnavaru island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'be632e70-63b0-8ca7-270c-9504e052f4c6', 'gallery', 1 from nodes where node_type = 'location' and slug = 'hinnavaru' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('217e976f-4144-24cd-b39c-0a6c4f53738c', 'image', 'uploads/assets/uploads/south/lhaviyani-kurendhoo-island.jpg', 'lhaviyani Kurendhoo island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '217e976f-4144-24cd-b39c-0a6c4f53738c', 'gallery', 1 from nodes where node_type = 'location' and slug = 'kurendhoo' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('06f36e7a-9826-c57b-529d-40b412f9ac5b', 'image', 'uploads/assets/uploads/south/lhaviyani-naifaru-island.jpg', 'lhaviyani Naifaru island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '06f36e7a-9826-c57b-529d-40b412f9ac5b', 'gallery', 1 from nodes where node_type = 'location' and slug = 'naifaru' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('79f20d1a-4ce3-5590-1a70-866ebee625ad', 'image', 'uploads/assets/uploads/south/lhaviyani-olhuvelifushi-island.jpg', 'lhaviyani Olhuvelifushi island') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '79f20d1a-4ce3-5590-1a70-866ebee625ad', 'gallery', 1 from nodes where node_type = 'location' and slug = 'olhuvelifushi' on conflict (node_id, media_id, role) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('b47f7b67-36c9-15fe-935d-6ccaad2db822', 'image', 'uploads/assets/uploads/south/lhaviyani-atoll-maldives.jpg', 'lhaviyani atoll maldives') on conflict (id) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'b47f7b67-36c9-15fe-935d-6ccaad2db822', 'gallery', 1 from nodes where node_type = 'location' and slug = 'lhaviyani' on conflict (node_id, media_id, role) do nothing;

