-- Task 20: transfer-category tagging + speedboat fleet + ferry schedule data.
-- GENERATED FILE - do not hand-edit. Regenerate with:
--   node scripts/build-transfers-platform-v2.mjs --commit

-- transfer-category taxonomy (Task 20 section 22: multi-category routes)
insert into nodes (id, node_type, slug, title, status, published_at) values ('43dc74cd-fcb4-33f6-7994-bba2d94938ee', 'category', 'airport', 'Airport Transfer', 'published', now()) on conflict (node_type, slug) do nothing;
insert into categories (id, category_group, path) select id, 'transfer-category', 'airport'::ltree from nodes where node_type = 'category' and slug = 'airport' on conflict (id) do nothing;
insert into nodes (id, node_type, slug, title, status, published_at) values ('09445182-a330-7da8-e73b-b19a481cfc9b', 'category', 'resort-transfer', 'Resort Transfer', 'published', now()) on conflict (node_type, slug) do nothing;
insert into categories (id, category_group, path) select id, 'transfer-category', 'resort_transfer'::ltree from nodes where node_type = 'category' and slug = 'resort-transfer' on conflict (id) do nothing;
insert into nodes (id, node_type, slug, title, status, published_at) values ('aa98d0c3-de69-e19b-6db0-574af13052db', 'category', 'hotel-transfer', 'Hotel Transfer', 'published', now()) on conflict (node_type, slug) do nothing;
insert into categories (id, category_group, path) select id, 'transfer-category', 'hotel_transfer'::ltree from nodes where node_type = 'category' and slug = 'hotel-transfer' on conflict (id) do nothing;
insert into nodes (id, node_type, slug, title, status, published_at) values ('e5475be2-5926-c875-752d-b317ddfbf15e', 'category', 'island-transfer', 'Island Transfer', 'published', now()) on conflict (node_type, slug) do nothing;
insert into categories (id, category_group, path) select id, 'transfer-category', 'island_transfer'::ltree from nodes where node_type = 'category' and slug = 'island-transfer' on conflict (id) do nothing;

-- tag every transfer_route: airport (origin is an airport), resort (destination not inhabited),
-- island (destination inhabited), hotel (destination inhabited AND has a real hotel/guesthouse accommodation)
insert into node_categories (node_id, category_id)
select tr.id, (select id from nodes where node_type = 'category' and slug = 'airport')
from transfer_routes tr
join locations ol on ol.id = tr.origin_location_id
where ol.location_type = 'airport'
on conflict do nothing;
insert into node_categories (node_id, category_id)
select tr.id, (select id from nodes where node_type = 'category' and slug = 'resort-transfer')
from transfer_routes tr
join locations dl on dl.id = tr.destination_location_id
where dl.is_inhabited = false
on conflict do nothing;
insert into node_categories (node_id, category_id)
select tr.id, (select id from nodes where node_type = 'category' and slug = 'island-transfer')
from transfer_routes tr
join locations dl on dl.id = tr.destination_location_id
where dl.is_inhabited = true
on conflict do nothing;
insert into node_categories (node_id, category_id)
select distinct tr.id, (select id from nodes where node_type = 'category' and slug = 'hotel-transfer')
from transfer_routes tr
join locations dl on dl.id = tr.destination_location_id
join node_locations nl on nl.location_id = dl.id
join accommodations acc on acc.id = nl.node_id
where dl.is_inhabited = true and acc.accommodation_type in ('hotel', 'guesthouse')
on conflict do nothing;

-- every route can take a private-transfer inquiry (Task 20 section 29), no fixed price
insert into bookable_products (id, booking_mode, base_price, currency, max_guests)
select id, 'inquiry', null, null, null from nodes where node_type = 'transfer_route'
on conflict (id) do nothing;

-- private charter speedboat fleet (7 real boats; owner stated 8 -- only 7 named, see migration report)
insert into nodes (id, node_type, slug, title, summary, status, meta_title, meta_description, published_at) values ('7cd49d50-c769-5d9b-0922-a68ecb21907b', 'speedboat', 'chill-speed', 'Chill Speed', '8-seat private charter speedboat, 25 ft, single engine (250 hp), top speed 28 knots. Available for hourly hire, destination-based charter, or a custom private trip - no fixed public price; request a charter quote.', 'published', 'Chill Speed Private Speedboat Charter | Maldives Tour Guide', 'Charter the Chill Speed, a 8-seat private speedboat in the Maldives. Hourly, destination-based, and custom charters available.', now()) on conflict (node_type, slug) do nothing;
insert into speedboats (id, capacity, length_feet, engine_count, horsepower, top_speed_knots, facilities, charter_options) select id, 8, 25, 1, 250, 28, '{}', ARRAY['Hourly hire', 'Destination-based charter', 'Custom trip']::text[] from nodes where node_type = 'speedboat' and slug = 'chill-speed' on conflict (id) do nothing;
insert into bookable_products (id, booking_mode, base_price, currency, max_guests) select id, 'inquiry', null, null, 8 from nodes where node_type = 'speedboat' and slug = 'chill-speed' on conflict (id) do nothing;
insert into nodes (id, node_type, slug, title, summary, status, meta_title, meta_description, published_at) values ('127cd584-5755-786e-dcdd-5ab5fbc391e2', 'speedboat', 'jupiter-11', 'Jupiter 11', '15-seat private charter speedboat, 28 ft, twin engine, top speed 32 knots. Available for hourly hire, destination-based charter, or a custom private trip - no fixed public price; request a charter quote.', 'published', 'Jupiter 11 Private Speedboat Charter | Maldives Tour Guide', 'Charter the Jupiter 11, a 15-seat private speedboat in the Maldives. Hourly, destination-based, and custom charters available.', now()) on conflict (node_type, slug) do nothing;
insert into speedboats (id, capacity, length_feet, engine_count, horsepower, top_speed_knots, facilities, charter_options) select id, 15, 28, 2, null, 32, '{}', ARRAY['Hourly hire', 'Destination-based charter', 'Custom trip']::text[] from nodes where node_type = 'speedboat' and slug = 'jupiter-11' on conflict (id) do nothing;
insert into bookable_products (id, booking_mode, base_price, currency, max_guests) select id, 'inquiry', null, null, 15 from nodes where node_type = 'speedboat' and slug = 'jupiter-11' on conflict (id) do nothing;
insert into nodes (id, node_type, slug, title, summary, status, meta_title, meta_description, published_at) values ('9a8a47d7-1b58-738e-99e5-d648f415dbdd', 'speedboat', 'chill-speed-2', 'Chill Speed 2', '18-seat private charter speedboat, 30 ft, twin engine, top speed 33 knots. Available for hourly hire, destination-based charter, or a custom private trip - no fixed public price; request a charter quote.', 'published', 'Chill Speed 2 Private Speedboat Charter | Maldives Tour Guide', 'Charter the Chill Speed 2, a 18-seat private speedboat in the Maldives. Hourly, destination-based, and custom charters available.', now()) on conflict (node_type, slug) do nothing;
insert into speedboats (id, capacity, length_feet, engine_count, horsepower, top_speed_knots, facilities, charter_options) select id, 18, 30, 2, null, 33, ARRAY['Toilet']::text[], ARRAY['Hourly hire', 'Destination-based charter', 'Custom trip']::text[] from nodes where node_type = 'speedboat' and slug = 'chill-speed-2' on conflict (id) do nothing;
insert into bookable_products (id, booking_mode, base_price, currency, max_guests) select id, 'inquiry', null, null, 18 from nodes where node_type = 'speedboat' and slug = 'chill-speed-2' on conflict (id) do nothing;
insert into nodes (id, node_type, slug, title, summary, status, meta_title, meta_description, published_at) values ('cb991f5e-ca46-7230-a79c-4360cf0a8415', 'speedboat', 'winover', 'Winover', '22-seat private charter speedboat, 32 ft, twin engine, top speed 35 knots. Available for hourly hire, destination-based charter, or a custom private trip - no fixed public price; request a charter quote.', 'published', 'Winover Private Speedboat Charter | Maldives Tour Guide', 'Charter the Winover, a 22-seat private speedboat in the Maldives. Hourly, destination-based, and custom charters available.', now()) on conflict (node_type, slug) do nothing;
insert into speedboats (id, capacity, length_feet, engine_count, horsepower, top_speed_knots, facilities, charter_options) select id, 22, 32, 2, null, 35, ARRAY['Toilet']::text[], ARRAY['Hourly hire', 'Destination-based charter', 'Custom trip']::text[] from nodes where node_type = 'speedboat' and slug = 'winover' on conflict (id) do nothing;
insert into bookable_products (id, booking_mode, base_price, currency, max_guests) select id, 'inquiry', null, null, 22 from nodes where node_type = 'speedboat' and slug = 'winover' on conflict (id) do nothing;
insert into nodes (id, node_type, slug, title, summary, status, meta_title, meta_description, published_at) values ('b3de2325-9f6d-7d0c-9b8a-99cbd7f3a4c0', 'speedboat', 'seaguard', 'Seaguard', '22-seat private charter speedboat, 36 ft, twin engine, top speed 36 knots. Available for hourly hire, destination-based charter, or a custom private trip - no fixed public price; request a charter quote.', 'published', 'Seaguard Private Speedboat Charter | Maldives Tour Guide', 'Charter the Seaguard, a 22-seat private speedboat in the Maldives. Hourly, destination-based, and custom charters available.', now()) on conflict (node_type, slug) do nothing;
insert into speedboats (id, capacity, length_feet, engine_count, horsepower, top_speed_knots, facilities, charter_options) select id, 22, 36, 2, null, 36, '{}', ARRAY['Hourly hire', 'Destination-based charter', 'Custom trip']::text[] from nodes where node_type = 'speedboat' and slug = 'seaguard' on conflict (id) do nothing;
insert into bookable_products (id, booking_mode, base_price, currency, max_guests) select id, 'inquiry', null, null, 22 from nodes where node_type = 'speedboat' and slug = 'seaguard' on conflict (id) do nothing;
insert into nodes (id, node_type, slug, title, summary, status, meta_title, meta_description, published_at) values ('8e4c22fe-b514-9f04-9d85-d8f24b61a3bf', 'speedboat', 'arriva', 'Arriva', '28-seat private charter speedboat, 38 ft. Available for hourly hire, destination-based charter, or a custom private trip - no fixed public price; request a charter quote.', 'published', 'Arriva Private Speedboat Charter | Maldives Tour Guide', 'Charter the Arriva, a 28-seat private speedboat in the Maldives. Hourly, destination-based, and custom charters available.', now()) on conflict (node_type, slug) do nothing;
insert into speedboats (id, capacity, length_feet, engine_count, horsepower, top_speed_knots, facilities, charter_options) select id, 28, 38, null, null, null, ARRAY['Air conditioning']::text[], ARRAY['Hourly hire', 'Destination-based charter', 'Custom trip']::text[] from nodes where node_type = 'speedboat' and slug = 'arriva' on conflict (id) do nothing;
insert into bookable_products (id, booking_mode, base_price, currency, max_guests) select id, 'inquiry', null, null, 28 from nodes where node_type = 'speedboat' and slug = 'arriva' on conflict (id) do nothing;
insert into nodes (id, node_type, slug, title, summary, status, meta_title, meta_description, published_at) values ('4cffc719-ec50-49ea-aa15-2cbc6fe111f5', 'speedboat', 'touring-43', 'Touring 43', '16-seat private charter speedboat, top speed 35 knots. Available for hourly hire, destination-based charter, or a custom private trip - no fixed public price; request a charter quote.', 'published', 'Touring 43 Private Speedboat Charter | Maldives Tour Guide', 'Charter the Touring 43, a 16-seat private speedboat in the Maldives. Hourly, destination-based, and custom charters available.', now()) on conflict (node_type, slug) do nothing;
insert into speedboats (id, capacity, length_feet, engine_count, horsepower, top_speed_knots, facilities, charter_options) select id, 16, null, null, null, 35, ARRAY['VIP interior', 'Air conditioning', 'Toilet', 'Luxury finish']::text[], ARRAY['Hourly hire', 'Destination-based charter', 'Custom trip']::text[] from nodes where node_type = 'speedboat' and slug = 'touring-43' on conflict (id) do nothing;
insert into bookable_products (id, booking_mode, base_price, currency, max_guests) select id, 'inquiry', null, null, 16 from nodes where node_type = 'speedboat' and slug = 'touring-43' on conflict (id) do nothing;

-- real ferry route images recovered from release/public_html/images/ferry/ (Task 20 section 2)
insert into media_assets (id, media_type, storage_path, alt_text) values ('ffd6ee63-6d63-f58c-c820-806354b742c6', 'image', 'legacy/images/ferry/kulhudhufushi-ferry-transfer.webp', 'Maldives province ferry schedule') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c2b9b196-dfef-f863-db02-323dab5feadf', 'image', 'legacy/images/ferry/manadhoo-ferry-schedule.webp', 'Maldives province ferry schedule') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('0efd6172-3488-e3cf-9e44-c3d5480f0653', 'image', 'legacy/images/ferry/noonu-atoll-ferry-transfer.webp', 'Maldives province ferry schedule') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('75f5c523-664c-689d-4dea-100cf466a73b', 'image', 'legacy/images/ferry/raa-atoll-transfer-schedule.webp', 'Maldives province ferry schedule') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('06f9023d-4ca8-bdec-b645-2ff2066ff509', 'image', 'legacy/images/ferry/maldives-ferry-transfer-schedules.webp', 'Maldives province ferry schedule') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a1ac62d5-efab-9389-3aec-f5a9f9f78871', 'image', 'legacy/images/ferry/alifu-atoll-ferry-transfer-schedule.webp', 'Maldives province ferry schedule') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3816c30e-7384-4502-f381-7022cf59ad3d', 'image', 'legacy/images/ferry/maldives-island-transfers-schedules.webp', 'Maldives province ferry schedule') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('4d34471f-a93b-6dae-2ef4-cdeaee1d08a0', 'image', 'legacy/images/ferry/vaavu-atoll-ferry-transfer-schedules.webp', 'Maldives province ferry schedule') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('3ac2a2fe-55c8-86ba-269b-b5d4d35e7043', 'image', 'legacy/images/ferry/maamigili-ferry-transfer-schedule.webp', 'Maldives province ferry schedule') on conflict (id) do nothing;

-- province ferry schedule (information only, no booking -- Task 20 section 25)
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('558adf41-92e0-74f3-e46c-f90e54f8e0cd', '101', null, 'Thuraakunu - Kulhudhuffushi', 'Upper North Province', 'Every Monday', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'thuraakunu'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'kulhudhuffushi'), '[{"island":"Thuraakunu","arrival":null,"departure":"06:00"},{"island":"Uligamu","arrival":"06:20","departure":"06:25"},{"island":"Mulhadhoo","arrival":"06:55","departure":"07:00"},{"island":"Dhidhoo","arrival":"08:15","departure":"08:20"},{"island":"Utheemu","arrival":"08:45","departure":"08:50"},{"island":"Kulhudhuffushi","arrival":"10:15","departure":"13:00"},{"island":"Utheemu","arrival":"14:25","departure":"14:30"},{"island":"Dhidhoo","arrival":"14:50","departure":"14:55"},{"island":"Mulhadhoo","arrival":"16:10","departure":"16:15"},{"island":"Uligamu","arrival":"16:55","departure":"17:00"},{"island":"Thuraakunu","arrival":"17:35","departure":null}]'::jsonb, 'ffd6ee63-6d63-f58c-c820-806354b742c6', '/maldives-transportation-ferry-speedboat-transfers.html', 0) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('4ec184d6-46b6-2a61-84ad-c1e749a701d7', '201', null, 'Henbadhoo - Manadhoo', 'North Province', 'Every Sat, Sun, Tue, Wed, Thu', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'henbadhoo'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'manadhoo'), '[{"island":"Henbadhoo","arrival":null,"departure":"07:00"},{"island":"Kendhikulhudhoo","arrival":"07:10","departure":"07:15"},{"island":"Kudafari","arrival":"07:45","departure":"07:50"},{"island":"Maalhendhoo","arrival":"08:10","departure":"08:15"},{"island":"Landhoo","arrival":"08:25","departure":"08:30"},{"island":"Maafaru","arrival":"09:00","departure":"09:05"},{"island":"Manadhoo","arrival":"09:40","departure":"14:00"},{"island":"Maafaru","arrival":"14:35","departure":"14:40"},{"island":"Landhoo","arrival":"15:10","departure":"15:15"},{"island":"Maalhendhoo","arrival":"15:25","departure":"15:30"},{"island":"Kudafari","arrival":"15:50","departure":"15:55"},{"island":"Kendhikulhudhoo","arrival":"16:25","departure":"16:30"},{"island":"Henbadhoo","arrival":"16:40","departure":null}]'::jsonb, 'c2b9b196-dfef-f863-db02-323dab5feadf', '/maldives-transportation-ferry-speedboat-transfers.html', 1) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('8abefa02-e296-ade9-d4c4-626f381bb608', '202', null, 'Velidhoo - Manadhoo', 'North Province', 'Every Sat, Sun, Tue, Wed, Thu', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'velidhoo'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'manadhoo'), '[{"island":"Velidhoo","arrival":null,"departure":"07:00"},{"island":"Fohdhoo","arrival":"07:40","departure":"07:45"},{"island":"Holhudhoo","arrival":"08:10","departure":"08:15"},{"island":"Magoodhoo","arrival":"08:55","departure":"09:00"},{"island":"Miladhoo","arrival":"09:10","departure":"09:15"},{"island":"Lhohi","arrival":"09:25","departure":"09:30"},{"island":"Manadhoo","arrival":"09:55","departure":"14:00"},{"island":"Lhohi","arrival":"14:25","departure":"14:30"},{"island":"Miladhoo","arrival":"14:40","departure":"14:45"},{"island":"Magoodhoo","arrival":"14:55","departure":"15:00"},{"island":"Holhudhoo","arrival":"15:20","departure":"15:25"},{"island":"Fohdhoo","arrival":"15:50","departure":"15:55"},{"island":"Velidhoo","arrival":"16:40","departure":null}]'::jsonb, '0efd6172-3488-e3cf-9e44-c3d5480f0653', '/maldives-transportation-ferry-speedboat-transfers.html', 2) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('b932d188-0b2e-a638-a5d9-ed234cbc469a', '203', null, 'Alifushi - Ungoofaaru', 'North Province', 'Everyday except Friday', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'alifushi'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'ungoofaaru'), '[{"island":"Alifushi","arrival":null,"departure":"06:10"},{"island":"Vaadhoo","arrival":"07:00","departure":"07:05"},{"island":"Rasgetheemu","arrival":"07:25","departure":"07:30"},{"island":"Angolhitheemu","arrival":"07:35","departure":"07:40"},{"island":"Hulhudhuffaaru","arrival":"08:00","departure":"08:05"},{"island":"Ifuru Airport","arrival":"08:25","departure":"08:30"},{"island":"Ungoofaaru","arrival":"08:50","departure":"14:30"},{"island":"Ifuru Airport","arrival":"14:50","departure":"14:55"},{"island":"Hulhudhuffaaru","arrival":"15:35","departure":"15:40"},{"island":"Angolhitheemu","arrival":"15:55","departure":"16:00"},{"island":"Rasgetheemu","arrival":"16:10","departure":"16:15"},{"island":"Vaadhoo","arrival":"16:35","departure":"16:40"},{"island":"Alifushi","arrival":"17:15","departure":null}]'::jsonb, '75f5c523-664c-689d-4dea-100cf466a73b', '/maldives-transportation-ferry-speedboat-transfers.html', 3) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('e84e23f5-57f6-d1f8-279a-368152835f70', '301', null, 'Himandhoo - Rasdhoo', 'North Central Province', 'Sat, Sun, Mon, Wed, Thu', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'himandhoo'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'rasdhoo'), '[{"island":"Himandhoo","arrival":null,"departure":"06:30"},{"island":"Maalhos","arrival":"07:00","departure":"07:05"},{"island":"Feridhoo","arrival":"07:30","departure":"07:35"},{"island":"Mathiveri","arrival":"08:30","departure":"08:35"},{"island":"Bodufolhudhoo","arrival":"08:55","departure":"09:00"},{"island":"Ukulhas","arrival":"09:35","departure":"09:40"},{"island":"Rasdhoo","arrival":"10:35","departure":"13:00"},{"island":"Ukulhas","arrival":"13:55","departure":"14:00"},{"island":"Bodufolhudhoo","arrival":"14:35","departure":"14:40"},{"island":"Mathiveri","arrival":"15:00","departure":"15:05"},{"island":"Feridhoo","arrival":"16:00","departure":"16:05"},{"island":"Maalhos","arrival":"16:30","departure":"16:35"},{"island":"Himandhoo","arrival":"17:05","departure":null}]'::jsonb, '06f9023d-4ca8-bdec-b645-2ff2066ff509', '/maldives-transportation-ferry-speedboat-transfers.html', 4) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('b0a8d505-6aab-e0ee-9359-8e91b9b3ca7d', '302', null, 'Mandhoo - Mahibadhoo', 'North Central Province', 'Sat, Sun, Tue, Wed, Thu', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'mandhoo'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'mahibadhoo'), '[{"island":"Mandhoo","arrival":null,"departure":"06:30"},{"island":"Kunburudhoo","arrival":"08:05","departure":"08:10"},{"island":"Mahibadhoo","arrival":"08:30","departure":"08:35"},{"island":"Haggnaameedhoo","arrival":"09:15","departure":"09:20"},{"island":"Omadhoo","arrival":"09:50","departure":"09:55"},{"island":"Mahibadhoo","arrival":"10:10","departure":"13:30"},{"island":"Omadhoo","arrival":"13:45","departure":"13:50"},{"island":"Haggnaameedhoo","arrival":"14:20","departure":"14:25"},{"island":"Mahibadhoo","arrival":"15:05","departure":"15:10"},{"island":"Kunburudhoo","arrival":"15:30","departure":"15:35"},{"island":"Mandhoo","arrival":"17:10","departure":null}]'::jsonb, 'a1ac62d5-efab-9389-3aec-f5a9f9f78871', '/maldives-transportation-ferry-speedboat-transfers.html', 5) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('32f9dea9-59fb-bea8-3be1-f422085b9cb7', '303', 'Mon & Thu', 'Male - Thoddoo', 'North Central Province', 'Monday & Thursday', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'male'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'thoddoo'), '[{"island":"Male","arrival":null,"departure":"09:00"},{"island":"Rasdhoo","arrival":"12:10","departure":"12:15"},{"island":"Ukulhas","arrival":"13:05","departure":"14:00"},{"island":"Rasdhoo","arrival":"14:50","departure":"15:10"},{"island":"Thoddoo","arrival":"16:20","departure":null}]'::jsonb, '3816c30e-7384-4502-f381-7022cf59ad3d', '/maldives-transportation-ferry-speedboat-transfers.html', 6) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('4b2800eb-7092-73fd-94bd-5d1d104366a3', '303', 'Sun & Wed', 'Thoddoo - Male', 'North Central Province', 'Sunday & Wednesday', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'thoddoo'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'male'), '[{"island":"Thoddoo","arrival":null,"departure":"06:30"},{"island":"Rasdhoo","arrival":"07:40","departure":"07:45"},{"island":"Ukulhas","arrival":"08:35","departure":"09:45"},{"island":"Rasdhoo","arrival":"10:35","departure":"11:00"},{"island":"Male","arrival":"14:10","departure":null}]'::jsonb, '3816c30e-7384-4502-f381-7022cf59ad3d', '/maldives-transportation-ferry-speedboat-transfers.html', 7) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('2d681411-3073-087c-63bf-01d2b3152042', '303', 'Sat & Tue', 'Thoddoo - Rasdhoo - Thoddoo', 'North Central Province', 'Saturday & Tuesday', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'thoddoo'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'thoddoo'), '[{"island":"Thoddoo","arrival":null,"departure":"07:00"},{"island":"Rasdhoo","arrival":"08:10","departure":"15:10"},{"island":"Thoddoo","arrival":"16:20","departure":null}]'::jsonb, '3816c30e-7384-4502-f381-7022cf59ad3d', '/maldives-transportation-ferry-speedboat-transfers.html', 8) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('2984efbd-419c-2f0e-cdd7-d1b3a33490f0', '304-305', 'Main loop', 'Fenfushi - Mahibadhoo', 'North Central Province', 'Sat, Sun, Tue, Wed, Thu', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'fenfushi'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'mahibadhoo'), '[{"island":"Fenfushi","arrival":null,"departure":"06:30"},{"island":"Maamigili","arrival":"06:55","departure":"07:00"},{"island":"Dhidhdhoo","arrival":"07:25","departure":"07:30"},{"island":"Dhigurah","arrival":"08:00","departure":"08:05"},{"island":"Dhangethi","arrival":"08:35","departure":"08:40"},{"island":"Mahibadhoo","arrival":"09:40","departure":"13:45"},{"island":"Dhangethi","arrival":"14:45","departure":"14:50"},{"island":"Dhigurah","arrival":"15:20","departure":"15:25"},{"island":"Dhidhdhoo","arrival":"15:55","departure":"16:00"},{"island":"Maamigili","arrival":"16:25","departure":"16:30"},{"island":"Fenfushi","arrival":"16:55","departure":null}]'::jsonb, '3ac2a2fe-55c8-86ba-269b-b5d4d35e7043', '/maldives-transportation-ferry-speedboat-transfers.html', 9) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('bb406dc7-f6f1-721c-f46f-e480d0c82318', '304-305', 'Male to Mahibadhoo connector', 'Male - Mahibadhoo', 'North Central Province', 'Sat, Mon, Wed', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'male'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'mahibadhoo'), '[{"island":"Male","arrival":null,"departure":"09:00"},{"island":"Mahibadhoo","arrival":"13:15","departure":null}]'::jsonb, '3ac2a2fe-55c8-86ba-269b-b5d4d35e7043', '/maldives-transportation-ferry-speedboat-transfers.html', 10) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('5f197371-4470-3c1e-532b-3d72374e31e7', '304-305', 'Mahibadhoo to Male connector', 'Mahibadhoo - Male', 'North Central Province', 'Sun, Tue, Thu', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'mahibadhoo'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'male'), '[{"island":"Mahibadhoo","arrival":null,"departure":"10:45"},{"island":"Male","arrival":"15:15","departure":null}]'::jsonb, '3ac2a2fe-55c8-86ba-269b-b5d4d35e7043', '/maldives-transportation-ferry-speedboat-transfers.html', 11) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('dbf0a6c4-44a2-a063-6e41-14c31487bdb8', '306', 'Rakeedhoo to Male', 'Rakeedhoo - Male', 'North Central Province', 'Sat, Mon, Wed', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'rakeedhoo'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'male'), '[{"island":"Rakeedhoo","arrival":null,"departure":"07:00"},{"island":"Keyodhoo","arrival":"08:05","departure":"08:10"},{"island":"Felidhoo","arrival":"08:20","departure":"08:25"},{"island":"Thinadhoo","arrival":"08:35","departure":"08:40"},{"island":"Fulidhoo","arrival":"10:05","departure":"10:30"},{"island":"Maafushi","arrival":"12:10","departure":"12:15"},{"island":"Male","arrival":"13:40","departure":null}]'::jsonb, '4d34471f-a93b-6dae-2ef4-cdeaee1d08a0', '/maldives-transportation-ferry-speedboat-transfers.html', 12) on conflict (id) do nothing;
insert into ferry_routes (id, route_number, variant_label, title, province, operating_days, origin_location_id, destination_location_id, stops, hero_media_id, source_legacy_url, sort_order) values ('b38fdfd5-5351-d688-aea1-89ecbebf26d8', '306', 'Male to Rakeedhoo', 'Male - Rakeedhoo', 'North Central Province', 'Sun, Tue, Thu', (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'male'), (select l.id from locations l join nodes n on n.id = l.id where n.node_type = 'location' and l.location_type = 'island' and n.slug = 'rakeedhoo'), '[{"island":"Male","arrival":null,"departure":"10:00"},{"island":"Maafushi","arrival":"11:25","departure":"11:30"},{"island":"Fulidhoo","arrival":"13:10","departure":"13:30"},{"island":"Thinadhoo","arrival":"14:55","departure":"15:00"},{"island":"Felidhoo","arrival":"15:10","departure":"15:15"},{"island":"Keyodhoo","arrival":"15:25","departure":"15:30"},{"island":"Rakeedhoo","arrival":"16:35","departure":null}]'::jsonb, '4d34471f-a93b-6dae-2ef4-cdeaee1d08a0', '/maldives-transportation-ferry-speedboat-transfers.html', 13) on conflict (id) do nothing;
