-- Owner-uploaded Male City Tour photos (assets/uploads/city-tour/) plus
-- 2 new bus-tour activities (mini bus USD 150/hr, large bus USD 200/hr),
-- requested alongside a unified /maldives/male-city-tour/ hub page.
-- GENERATED FILE, regenerate with:
--   node scripts/attach-city-tour-uploads.mjs --commit

insert into media_assets (id, media_type, storage_path, alt_text) values ('4df88452-c36b-a89b-24fb-ad0c838516d3', 'image', 'uploads/assets/uploads/city-tour/male-city-bridge.webp', 'male city bridge - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('a1e08c4e-ecf4-ed91-7ffe-dd407169706d', 'image', 'uploads/assets/uploads/city-tour/male-city-harbour.webp', 'male city harbour - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('d5859ef5-1b65-30dd-c3b5-4bc47f2fe3fc', 'image', 'uploads/assets/uploads/city-tour/muleeaage-male-city.webp', 'muleeaage male city - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('8a826e21-8255-0807-4e3a-7d2d4cea416e', 'image', 'uploads/assets/uploads/city-tour/male-city-stingray-point.webp', 'male city stingray point - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('c3c4e389-4fc9-9136-d4cd-b015dbab0ba3', 'image', 'uploads/assets/uploads/city-tour/male-city-artificial-beach.webp', 'male city artificial beach - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('8ca42eb1-16a3-2863-f469-ab618a7033e4', 'image', 'uploads/assets/uploads/city-tour/male-arial.webp', 'male arial - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('853caee9-8472-2a6c-e7c5-75249203c10e', 'image', 'uploads/assets/uploads/city-tour/maldives-capital-city-tour.webp', 'maldives capital city tour - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('730b3f5a-d895-e79b-1031-c1149719294e', 'image', 'uploads/assets/uploads/city-tour/male-maldives.webp', 'male maldives - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('51bbcb0b-96f2-7630-6017-4680776e8c4d', 'image', 'uploads/assets/uploads/city-tour/male-city-guided-tour.webp', 'male city guided tour - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('eb84e72f-5fdc-32ee-8d72-fbbf4d551e07', 'image', 'uploads/assets/uploads/city-tour/male-bike-tour.webp', 'male bike tour - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('9aa62cf4-1d6e-b25a-2565-cddd5a4cacf5', 'image', 'uploads/assets/uploads/city-tour/male-city-car-tour.png', 'male city car tour - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('27c7fc2b-ed6d-9b8c-0134-8461a19ec681', 'image', 'uploads/assets/uploads/city-tour/maldives-historical-tour.webp', 'maldives historical tour - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('1cd53b0d-e612-ac43-e063-0580cae9e219', 'image', 'uploads/assets/uploads/city-tour/visit-male-city.webp', 'visit male city - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('ac03fc8a-a8d1-807f-d62d-f0141be78814', 'image', 'uploads/assets/uploads/city-tour/male-island-tour.webp', 'male island tour - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('d337e441-23cc-6616-436b-545a856d064d', 'image', 'uploads/assets/uploads/city-tour/male-city.webp', 'male city - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('ade3cf58-2fa8-9254-72c8-340beccd14de', 'image', 'uploads/assets/uploads/city-tour/maldives-bus-tour.webp', 'maldives bus tour - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('1a26290a-9d92-633b-0f2c-4e9927274e3b', 'image', 'uploads/assets/uploads/city-tour/male-city-bus-tour.jpeg', 'male city bus tour - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('8641a1c3-bb88-f728-263f-8518dfe4685d', 'image', 'uploads/assets/uploads/city-tour/male-city-tour.webp', 'male city tour - Male City Tour') on conflict (id) do nothing;
insert into media_assets (id, media_type, storage_path, alt_text) values ('eed208cc-0eec-439b-7b3a-e1e07b3d3a24', 'image', 'uploads/assets/uploads/city-tour/maldives-city-tour.webp', 'maldives city tour - Male City Tour') on conflict (id) do nothing;

-- Activity: Male City Mini Bus Tour (USD 150/hour)
insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, published_at) values ('activity', 'male-city-mini-bus-tour', 'Male City Mini Bus Tour', 'Male City Mini Bus Tour is a guided sightseeing tour of Male, the Maldives'' capital island, by air-conditioned mini bus (up to ~15 seats), with airport pickup and drop-off. USD 150 per hour, minimum 2 hours. Includes: airport pickup and drop-off, local guide, mini bus, taxes. Highlights: Stingray Point, local market, fish market, souvenir street, Old Presidential Palace, Grand Friday Mosque, Victory Monument, Old Friday Mosque (heritage), Presidential Office, Parliament, Artificial Beach, surfing point, Tsunami Monument, King Salmaan Mosque, and the Sinamale Bridge.', 'published', 'Male City Mini Bus Tour (USD 150/hr) | Maldives Tour Guide', 'Male City Mini Bus Tour is a guided sightseeing tour of Male by air-conditioned mini bus, with airport pickup and drop-off. USD 150 per hour.', now()) on conflict (node_type, slug) do nothing;
insert into activities (id, activity_category, operated_by_provider_id, price_from, currency) select n.id, 'excursion', p.id, 150, 'USD' from nodes n, nodes p where n.node_type = 'activity' and n.slug = 'male-city-mini-bus-tour' and p.node_type = 'provider' and p.slug = 'maldives-tour-guide-tours' on conflict (id) do nothing;
insert into node_locations (node_id, location_id, relation) select n.id, l.id, 'primary' from nodes n, nodes l where n.node_type = 'activity' and n.slug = 'male-city-mini-bus-tour' and l.node_type = 'location' and l.slug = 'male' on conflict (node_id, location_id) do nothing;
insert into bookable_products (id, booking_mode, base_price, currency) select id, 'inquiry', 150, 'USD' from nodes where node_type = 'activity' and slug = 'male-city-mini-bus-tour' on conflict (id) do nothing;
insert into node_categories (node_id, category_id) select n.id, c.id from nodes n, nodes c where n.node_type = 'activity' and n.slug = 'male-city-mini-bus-tour' and c.node_type = 'category' and c.slug = 'city-tour' on conflict (node_id, category_id) do nothing;

-- Activity: Male City Large Bus Tour (USD 200/hour)
insert into nodes (node_type, slug, title, summary, status, meta_title, meta_description, published_at) values ('activity', 'male-city-large-bus-tour', 'Male City Large Bus Tour', 'Male City Large Bus Tour is a guided sightseeing tour of Male, the Maldives'' capital island, by air-conditioned large bus (30+ seats), ideal for bigger groups, with airport pickup and drop-off. USD 200 per hour, minimum 2 hours. Includes: airport pickup and drop-off, local guide, large bus, taxes. Highlights: Stingray Point, local market, fish market, souvenir street, Old Presidential Palace, Grand Friday Mosque, Victory Monument, Old Friday Mosque (heritage), Presidential Office, Parliament, Artificial Beach, surfing point, Tsunami Monument, King Salmaan Mosque, and the Sinamale Bridge.', 'published', 'Male City Large Bus Tour (USD 200/hr) | Maldives Tour Guide', 'Male City Large Bus Tour is a guided sightseeing tour of Male by air-conditioned large bus, ideal for groups, with airport pickup and drop-off. USD 200 per hour.', now()) on conflict (node_type, slug) do nothing;
insert into activities (id, activity_category, operated_by_provider_id, price_from, currency) select n.id, 'excursion', p.id, 200, 'USD' from nodes n, nodes p where n.node_type = 'activity' and n.slug = 'male-city-large-bus-tour' and p.node_type = 'provider' and p.slug = 'maldives-tour-guide-tours' on conflict (id) do nothing;
insert into node_locations (node_id, location_id, relation) select n.id, l.id, 'primary' from nodes n, nodes l where n.node_type = 'activity' and n.slug = 'male-city-large-bus-tour' and l.node_type = 'location' and l.slug = 'male' on conflict (node_id, location_id) do nothing;
insert into bookable_products (id, booking_mode, base_price, currency) select id, 'inquiry', 200, 'USD' from nodes where node_type = 'activity' and slug = 'male-city-large-bus-tour' on conflict (id) do nothing;
insert into node_categories (node_id, category_id) select n.id, c.id from nodes n, nodes c where n.node_type = 'activity' and n.slug = 'male-city-large-bus-tour' and c.node_type = 'category' and c.slug = 'city-tour' on conflict (node_id, category_id) do nothing;

-- male-city-walking-tour: hero + gallery from owner uploads
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'male-city-walking-tour');
insert into node_media (node_id, media_id, role, sort_order) select id, '51bbcb0b-96f2-7630-6017-4680776e8c4d', 'hero', 0 from nodes where node_type = 'activity' and slug = 'male-city-walking-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '4df88452-c36b-a89b-24fb-ad0c838516d3', 'gallery', 10 from nodes where node_type = 'activity' and slug = 'male-city-walking-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a1e08c4e-ecf4-ed91-7ffe-dd407169706d', 'gallery', 11 from nodes where node_type = 'activity' and slug = 'male-city-walking-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'c3c4e389-4fc9-9136-d4cd-b015dbab0ba3', 'gallery', 12 from nodes where node_type = 'activity' and slug = 'male-city-walking-tour' on conflict (node_id, media_id, role) do nothing;

-- male-city-bike-tour: hero + gallery from owner uploads
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'male-city-bike-tour');
insert into node_media (node_id, media_id, role, sort_order) select id, 'eb84e72f-5fdc-32ee-8d72-fbbf4d551e07', 'hero', 0 from nodes where node_type = 'activity' and slug = 'male-city-bike-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8a826e21-8255-0807-4e3a-7d2d4cea416e', 'gallery', 10 from nodes where node_type = 'activity' and slug = 'male-city-bike-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '4df88452-c36b-a89b-24fb-ad0c838516d3', 'gallery', 11 from nodes where node_type = 'activity' and slug = 'male-city-bike-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8ca42eb1-16a3-2863-f469-ab618a7033e4', 'gallery', 12 from nodes where node_type = 'activity' and slug = 'male-city-bike-tour' on conflict (node_id, media_id, role) do nothing;

-- male-city-car-tour: hero + gallery from owner uploads
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'male-city-car-tour');
insert into node_media (node_id, media_id, role, sort_order) select id, '9aa62cf4-1d6e-b25a-2565-cddd5a4cacf5', 'hero', 0 from nodes where node_type = 'activity' and slug = 'male-city-car-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a1e08c4e-ecf4-ed91-7ffe-dd407169706d', 'gallery', 10 from nodes where node_type = 'activity' and slug = 'male-city-car-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '853caee9-8472-2a6c-e7c5-75249203c10e', 'gallery', 11 from nodes where node_type = 'activity' and slug = 'male-city-car-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8ca42eb1-16a3-2863-f469-ab618a7033e4', 'gallery', 12 from nodes where node_type = 'activity' and slug = 'male-city-car-tour' on conflict (node_id, media_id, role) do nothing;

-- male-city-half-day-walking-tour: hero + gallery from owner uploads
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'male-city-half-day-walking-tour');
insert into node_media (node_id, media_id, role, sort_order) select id, '27c7fc2b-ed6d-9b8c-0134-8461a19ec681', 'hero', 0 from nodes where node_type = 'activity' and slug = 'male-city-half-day-walking-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'd5859ef5-1b65-30dd-c3b5-4bc47f2fe3fc', 'gallery', 10 from nodes where node_type = 'activity' and slug = 'male-city-half-day-walking-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '730b3f5a-d895-e79b-1031-c1149719294e', 'gallery', 11 from nodes where node_type = 'activity' and slug = 'male-city-half-day-walking-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '1cd53b0d-e612-ac43-e063-0580cae9e219', 'gallery', 12 from nodes where node_type = 'activity' and slug = 'male-city-half-day-walking-tour' on conflict (node_id, media_id, role) do nothing;

-- male-city-half-day-bike-tour: hero + gallery from owner uploads
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'male-city-half-day-bike-tour');
insert into node_media (node_id, media_id, role, sort_order) select id, 'ac03fc8a-a8d1-807f-d62d-f0141be78814', 'hero', 0 from nodes where node_type = 'activity' and slug = 'male-city-half-day-bike-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8a826e21-8255-0807-4e3a-7d2d4cea416e', 'gallery', 10 from nodes where node_type = 'activity' and slug = 'male-city-half-day-bike-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '730b3f5a-d895-e79b-1031-c1149719294e', 'gallery', 11 from nodes where node_type = 'activity' and slug = 'male-city-half-day-bike-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'd337e441-23cc-6616-436b-545a856d064d', 'gallery', 12 from nodes where node_type = 'activity' and slug = 'male-city-half-day-bike-tour' on conflict (node_id, media_id, role) do nothing;

-- male-city-mini-bus-tour: hero + gallery from owner uploads
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'male-city-mini-bus-tour');
insert into node_media (node_id, media_id, role, sort_order) select id, 'ade3cf58-2fa8-9254-72c8-340beccd14de', 'hero', 0 from nodes where node_type = 'activity' and slug = 'male-city-mini-bus-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a1e08c4e-ecf4-ed91-7ffe-dd407169706d', 'gallery', 10 from nodes where node_type = 'activity' and slug = 'male-city-mini-bus-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '853caee9-8472-2a6c-e7c5-75249203c10e', 'gallery', 11 from nodes where node_type = 'activity' and slug = 'male-city-mini-bus-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8ca42eb1-16a3-2863-f469-ab618a7033e4', 'gallery', 12 from nodes where node_type = 'activity' and slug = 'male-city-mini-bus-tour' on conflict (node_id, media_id, role) do nothing;

-- male-city-large-bus-tour: hero + gallery from owner uploads
delete from node_media where role = 'hero' and node_id = (select id from nodes where node_type = 'activity' and slug = 'male-city-large-bus-tour');
insert into node_media (node_id, media_id, role, sort_order) select id, '1a26290a-9d92-633b-0f2c-4e9927274e3b', 'hero', 0 from nodes where node_type = 'activity' and slug = 'male-city-large-bus-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, 'a1e08c4e-ecf4-ed91-7ffe-dd407169706d', 'gallery', 10 from nodes where node_type = 'activity' and slug = 'male-city-large-bus-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '853caee9-8472-2a6c-e7c5-75249203c10e', 'gallery', 11 from nodes where node_type = 'activity' and slug = 'male-city-large-bus-tour' on conflict (node_id, media_id, role) do nothing;
insert into node_media (node_id, media_id, role, sort_order) select id, '8641a1c3-bb88-f728-263f-8518dfe4685d', 'gallery', 12 from nodes where node_type = 'activity' and slug = 'male-city-large-bus-tour' on conflict (node_id, media_id, role) do nothing;

-- Redirect the legacy single-page URL to the new unified hub page.
insert into url_redirects (source_path, target_type, target_path, status_code, notes) values ('/male-city-tour.html', 'path', '/maldives/male-city-tour/', 301, '[redirect, confidence=high] Updated to the new unified Male City Tour hub page listing all 7 tour options (was pointing at just the walking-tour activity page).') on conflict (source_path) do update set target_type = excluded.target_type, target_path = excluded.target_path, status_code = excluded.status_code, notes = excluded.notes, updated_at = now();

