import type { PackageCategorySlug, PackagePriceType } from "@/lib/packages/view-types";

/**
 * Task 21 §14/§37: the owner's demo package inventory, since real
 * commercial packages aren't ready yet (only 6 exist — see
 * data/maldives/packages/packages.json). Every one of these is plain
 * TypeScript data, clearly isolated from real DB-backed packages, marked
 * `isDemo: true` wherever it surfaces in the UI — never presented as a
 * real commercial offer, never given fabricated Review/AggregateRating
 * structured data (see demo.ts and view.ts).
 *
 * "Demo" describes the PACKAGE (its existence as a bookable product, its
 * price, its rating) — not its content. Every package below is anchored
 * to a REAL accommodation and/or REAL activities already in this
 * project's catalogue (accommodationSlug/activitySlugs resolve against
 * the live accommodations/activities repositories in demo.ts), so its
 * image, destination, and "See also" links are all genuine. Only 6
 * accommodations currently have no matching legacy photo at all
 * (see scripts/attach-accommodation-images.mjs's report) — packages
 * anchored to those fall back to a real, category-appropriate legacy
 * image (category-images.ts) rather than going imageless.
 *
 * To replace this with real commercial inventory later: stop importing
 * from this file in view-repository.ts's getAllPackageViews() and either
 * delete individual entries here or swap the whole array for real
 * `packages` DB rows built the same way the existing 6 were (Task 11) —
 * no other file changes needed, since every UI component only ever reads
 * the shared PackageView type.
 */

export interface DemoItineraryDay {
  day: number;
  title: string;
  description: string;
  /** Real activity slugs referenced this day, if any. */
  activitySlugs?: string[];
}

export interface DemoPackageInput {
  slug: string;
  title: string;
  shortDescription: string;
  description: string;
  categories: PackageCategorySlug[];
  nights: number;
  price: number;
  currency: string;
  priceType: PackagePriceType;
  rating: number;
  ratingCount: number;
  highlights: string[];
  bestFor: string[];
  included: string[];
  transferIncluded: boolean;
  transferLabel?: string;
  mealsIncluded: string | null;
  flightIncluded: boolean;
  /** The real accommodation this package stays at — resolved via
   * getAccommodationBySlug in demo.ts for its real location/image/link. */
  accommodationSlug?: string;
  /** Real activities this package includes, resolved via
   * getActivityBySlug — never invented operators/excursions. */
  activitySlugs?: string[];
  /** Only for packages with no accommodation anchor (e.g. liveaboard) —
   * a real atoll slug for the destination/location filter. */
  atollSlug?: string;
  itinerary: DemoItineraryDay[];
  createdAt: string;
}

export const DEMO_PACKAGES: DemoPackageInput[] = [
  {
    slug: "maldives-luxury-overwater-escape",
    title: "Maldives Luxury Overwater Escape",
    shortDescription: "Seven nights of barefoot luxury at Soneva Fushi, Baa Atoll's all-inclusive island resort.",
    description:
      "A slow, indulgent week at Soneva Fushi — over-water and beachfront villas, an in-house dive centre, and the kind of private-island quiet that's hard to find anywhere else in the Maldives.",
    categories: ["luxury", "honeymoon", "long-stay"],
    nights: 7,
    price: 5499,
    currency: "USD",
    priceType: "per-couple",
    rating: 4.9,
    ratingCount: 38,
    highlights: ["All-inclusive over-water villa stay", "Guided reef dive included", "Private-island seaplane arrival"],
    bestFor: ["Couples", "Honeymooners", "Luxury travelers"],
    included: ["Accommodation", "All meals", "Guided reef dive", "Return seaplane transfer"],
    transferIncluded: true,
    transferLabel: "Seaplane",
    mealsIncluded: "All meals",
    flightIncluded: false,
    accommodationSlug: "soneva-fushi",
    activitySlugs: ["guided-reef-dive"],
    itinerary: [
      { day: 1, title: "Arrival & seaplane transfer", description: "Land at Velana International Airport and continue by seaplane straight to Soneva Fushi in Baa Atoll." },
      { day: 2, title: "Settle in", description: "A full day to explore the island on foot or by bicycle — no schedule, no itinerary." },
      { day: 3, title: "Guided reef dive", description: "A guided reef dive through the resort's own dive centre.", activitySlugs: ["guided-reef-dive"] },
      { day: 4, title: "Free day", description: "Spa, beach, or simply the villa's own deck." },
      { day: 5, title: "Sandbank excursion", description: "An optional trip to a nearby sandbank for the afternoon." },
      { day: 6, title: "Free day", description: "Another unstructured day — the point of Soneva Fushi." },
      { day: 7, title: "Departure", description: "Seaplane transfer back to Velana International Airport for your onward flight." },
    ],
    createdAt: "2026-01-05",
  },
  {
    slug: "six-senses-laamu-luxury-retreat",
    title: "Six Senses Laamu Luxury Retreat",
    shortDescription: "Five nights at Six Senses Laamu, one atoll away from the usual North Malé crowds.",
    description: "Laamu Atoll is a longer flight from the airport than most resorts, which is exactly why Six Senses Laamu stays quieter — overwater villas, a real house reef, and a genuinely private feel.",
    categories: ["luxury", "adults-only"],
    nights: 5,
    price: 3899,
    currency: "USD",
    priceType: "per-couple",
    rating: 4.8,
    ratingCount: 27,
    highlights: ["Overwater villa with house reef access", "Domestic flight + speedboat transfer", "A quieter, less-visited atoll"],
    bestFor: ["Couples", "Luxury travelers"],
    included: ["Accommodation", "Breakfast daily"],
    transferIncluded: true,
    transferLabel: "Domestic flight + speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "six-senses-laamu",
    itinerary: [
      { day: 1, title: "Arrival", description: "Domestic flight from Velana International Airport to Kadhdhoo, then a short speedboat transfer to the resort." },
      { day: 2, title: "House reef", description: "Snorkel the resort's own house reef, a short swim from your villa." },
      { day: 3, title: "Free day", description: "Spa, water sports, or simply the villa." },
      { day: 4, title: "Free day", description: "Sunset by the beach, dinner at one of the resort's restaurants." },
      { day: 5, title: "Departure", description: "Speedboat and domestic flight back to Velana International Airport." },
    ],
    createdAt: "2026-01-05",
  },
  {
    slug: "gili-lankanfushi-barefoot-luxury",
    title: "Gili Lankanfushi Barefoot Luxury",
    shortDescription: "Six nights at Gili Lankanfushi — a genuinely shoe-free, overwater luxury resort in North Malé Atoll.",
    description: "Gili Lankanfushi's whole concept is 'no news, no shoes' — overwater villas connected by wooden walkways, a private island feel just a 20-minute speedboat ride from the airport.",
    categories: ["luxury", "honeymoon", "adults-only"],
    nights: 6,
    price: 4799,
    currency: "USD",
    priceType: "per-couple",
    rating: 4.9,
    ratingCount: 41,
    highlights: ["Overwater villa with private pool", "20-minute speedboat from the airport", "Discover Scuba Diving session included"],
    bestFor: ["Couples", "Honeymooners"],
    included: ["Accommodation", "Breakfast daily", "Discover Scuba Diving session"],
    transferIncluded: true,
    transferLabel: "Speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "gili-lankanfushi",
    activitySlugs: ["discover-scuba-diving-lankanfushi"],
    itinerary: [
      { day: 1, title: "Arrival & speedboat transfer", description: "A short, scenic speedboat ride from Velana International Airport to the resort." },
      { day: 2, title: "Discover Scuba Diving", description: "A supervised introductory dive for first-timers or refreshers.", activitySlugs: ["discover-scuba-diving-lankanfushi"] },
      { day: 3, title: "Free day", description: "Overwater villa, private pool, no schedule." },
      { day: 4, title: "Free day", description: "Snorkeling off the house reef or a spa treatment." },
      { day: 5, title: "Sunset cruise", description: "An evening on the water as the sun goes down." },
      { day: 6, title: "Departure", description: "Speedboat transfer back to Velana International Airport." },
    ],
    createdAt: "2026-01-04",
  },
  {
    slug: "tropical-maldives-honeymoon-baros",
    title: "Tropical Maldives Honeymoon — Baros",
    shortDescription: "Seven romantic nights at Baros Maldives, one of North Malé Atoll's longest-established resorts.",
    description: "Baros has been running since 1973 and it shows in how well-run the whole island feels — this itinerary keeps things simple: overwater villa, real dive centre, and time to actually relax.",
    categories: ["honeymoon", "luxury", "adults-only"],
    nights: 7,
    price: 5199,
    currency: "USD",
    priceType: "per-couple",
    rating: 4.8,
    ratingCount: 52,
    highlights: ["Overwater villa", "Fluorescence night dive included", "15-minute speedboat from the airport"],
    bestFor: ["Couples", "Honeymooners"],
    included: ["Accommodation", "Breakfast daily", "Fluo night dive"],
    transferIncluded: true,
    transferLabel: "Speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "baros-maldives",
    activitySlugs: ["fluo-night-diving"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Speedboat transfer from Velana International Airport, about 15 minutes." },
      { day: 2, title: "Settle in", description: "A full free day to explore the island and reef." },
      { day: 3, title: "Fluorescence night dive", description: "A real fluo night dive through Baros's own long-established dive centre.", activitySlugs: ["fluo-night-diving"] },
      { day: 4, title: "Free day", description: "Spa, beach, or the villa's own deck." },
      { day: 5, title: "Private dinner", description: "An evening set up for two on the beach." },
      { day: 6, title: "Free day", description: "Snorkeling the house reef one more time." },
      { day: 7, title: "Departure", description: "Speedboat transfer back to Velana International Airport." },
    ],
    createdAt: "2026-01-03",
  },
  {
    slug: "maldives-family-island-adventure-kurumba",
    title: "Maldives Family Island Adventure",
    shortDescription: "Six nights at Kurumba Maldives, the country's first resort and a short hop from the airport.",
    description: "Kurumba is close to the airport (useful with kids), has a large enough island to actually roam, and a real range of family-friendly activities on record.",
    categories: ["family"],
    nights: 6,
    price: 2899,
    currency: "USD",
    priceType: "per-package",
    rating: 4.5,
    ratingCount: 63,
    highlights: ["10-minute speedboat from the airport", "Sunset reef fishing trip included", "Large island with space to roam"],
    bestFor: ["Families", "Couples with children"],
    included: ["Accommodation", "Breakfast daily", "Sunset reef fishing trip"],
    transferIncluded: true,
    transferLabel: "Speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "kurumba-maldives",
    itinerary: [
      { day: 1, title: "Arrival", description: "A short 10-minute speedboat transfer from Velana International Airport." },
      { day: 2, title: "Settle in", description: "Pool, beach, and getting the kids used to island time." },
      { day: 3, title: "Sunset reef fishing", description: "A family-friendly evening fishing trip on Kurumba's own boat." },
      { day: 4, title: "Free day", description: "Water sports centre or a lazy pool day." },
      { day: 5, title: "Island exploring", description: "Kurumba's island is large enough for a proper walk or bike ride." },
      { day: 6, title: "Departure", description: "Speedboat transfer back to Velana International Airport." },
    ],
    createdAt: "2026-01-06",
  },
  {
    slug: "velassaru-family-beach-holiday",
    title: "Velassaru Family Beach Holiday",
    shortDescription: "Six nights at Velassaru Maldives, a mid-size resort with a real range of activities on record.",
    description: "Velassaru sits close enough to Malé for an easy transfer, with both a genuine dive centre and sport fishing charter already on record — a package built entirely from things this resort actually does.",
    categories: ["family", "luxury"],
    nights: 6,
    price: 3299,
    currency: "USD",
    priceType: "per-package",
    rating: 4.6,
    ratingCount: 45,
    highlights: ["Discover Scuba Diving session included", "Big game fishing trip included", "20-minute speedboat from the airport"],
    bestFor: ["Families", "Couples"],
    included: ["Accommodation", "Breakfast daily", "Discover Scuba Diving session", "Big game fishing trip"],
    transferIncluded: true,
    transferLabel: "Speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "velassaru-maldives",
    activitySlugs: ["discover-scuba-diving-velassaru", "big-game-fishing-trip"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Speedboat transfer from Velana International Airport, about 20 minutes." },
      { day: 2, title: "Discover Scuba Diving", description: "A supervised introductory dive session.", activitySlugs: ["discover-scuba-diving-velassaru"] },
      { day: 3, title: "Big game fishing trip", description: "A half-day sport fishing charter with the resort's own operator.", activitySlugs: ["big-game-fishing-trip"] },
      { day: 4, title: "Free day", description: "Beach, pool, or the resort's water sports centre." },
      { day: 5, title: "Free day", description: "One more day to enjoy the island before departure." },
      { day: 6, title: "Departure", description: "Speedboat transfer back to Velana International Airport." },
    ],
    createdAt: "2026-01-06",
  },
  {
    slug: "maldives-budget-beach-holiday-maafushi",
    title: "Maldives Budget Beach Holiday",
    shortDescription: "Five nights at Arena Beach Hotel on Maafushi, a popular local island in Kaafu Atoll.",
    description: "Maafushi is the classic budget-friendly Maldives base — a real inhabited local island with its own beach, guesthouses and hotels, and genuine dive/fishing operators, at a fraction of resort prices.",
    categories: ["budget"],
    nights: 5,
    price: 799,
    currency: "USD",
    priceType: "per-person",
    rating: 4.3,
    ratingCount: 71,
    highlights: ["Local island stay, real Maldivian life", "Sunset fishing trip included", "A fraction of resort-island prices"],
    bestFor: ["Budget travelers", "First-time visitors"],
    included: ["Accommodation", "Breakfast daily", "Sunset fishing trip"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "arena-beach-hotel",
    activitySlugs: ["sunset-fishing-trip-maafushi"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Public ferry or speedboat transfer from Malé to Maafushi." },
      { day: 2, title: "Settle in", description: "Maafushi's own bikini beach and the town itself." },
      { day: 3, title: "Sunset fishing trip", description: "A real local sunset fishing trip, a Maafushi speciality.", activitySlugs: ["sunset-fishing-trip-maafushi"] },
      { day: 4, title: "Free day", description: "Optional snorkeling or sandbank trip, arranged locally." },
      { day: 5, title: "Departure", description: "Ferry or speedboat transfer back to Malé for your onward journey." },
    ],
    createdAt: "2026-01-07",
  },
  {
    slug: "maafushi-local-island-getaway",
    title: "Maafushi Local Island Getaway",
    shortDescription: "Four nights at Kaani Beach Hotel on Maafushi, with a real diving course included.",
    description: "A shorter Maafushi stay built around Kaani Beach Hotel and two real diving courses already on record at this hotel — genuinely useful if you want to start (or continue) certification affordably.",
    categories: ["budget", "solo", "diving"],
    nights: 4,
    price: 649,
    currency: "USD",
    priceType: "per-person",
    rating: 4.4,
    ratingCount: 34,
    highlights: ["Advanced Open Water course included", "Local island budget stay", "Easy to extend or shorten"],
    bestFor: ["Budget travelers", "Solo travelers", "Divers"],
    included: ["Accommodation", "Breakfast daily", "Advanced Open Water Diver Course"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "kaani-beach-hotel",
    activitySlugs: ["advanced-open-water-diver-course"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Ferry or speedboat transfer from Malé to Maafushi." },
      { day: 2, title: "Advanced Open Water course, day 1", description: "Classroom and pool sessions begin.", activitySlugs: ["advanced-open-water-diver-course"] },
      { day: 3, title: "Advanced Open Water course, day 2", description: "Open-water dives to complete certification.", activitySlugs: ["advanced-open-water-diver-course"] },
      { day: 4, title: "Departure", description: "Ferry or speedboat transfer back to Malé." },
    ],
    createdAt: "2026-01-07",
  },
  {
    slug: "maldives-long-stay-island-escape-gulhi",
    title: "Maldives Long Stay Island Escape",
    shortDescription: "Fourteen nights at Crystal View Maldives Guest House on Gulhi, a quiet local island in Kaafu Atoll.",
    description: "Gulhi is smaller and quieter than Maafushi, making it a genuinely good base for a proper long stay without resort prices — this is a slow, low-key two weeks, not a packed itinerary.",
    categories: ["long-stay", "budget", "solo"],
    nights: 14,
    price: 1899,
    currency: "USD",
    priceType: "per-person",
    rating: 4.2,
    ratingCount: 19,
    highlights: ["Two full weeks on a quiet local island", "Budget-friendly long-stay rate", "Easy day trips to nearby islands"],
    bestFor: ["Long-stay travelers", "Budget travelers", "Solo travelers"],
    included: ["Accommodation", "Breakfast daily"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "crystal-view-maldives-guest-house",
    itinerary: [
      { day: 1, title: "Arrival", description: "Ferry or speedboat transfer from Malé to Gulhi." },
      { day: 2, title: "Settle in", description: "The first few days are unstructured — get to know the island." },
      { day: 7, title: "Midway", description: "Optional day trip to a nearby island or sandbank, arranged locally." },
      { day: 14, title: "Departure", description: "Ferry or speedboat transfer back to Malé for your onward journey." },
    ],
    createdAt: "2026-01-02",
  },
  {
    slug: "extended-kurumba-resort-stay",
    title: "Extended Kurumba Resort Stay",
    shortDescription: "Fifteen nights at Kurumba Maldives — a genuine long-stay resort itinerary, not a padded 7-night trip.",
    description: "For travelers who want a resort-island long stay rather than a short getaway — Kurumba's proximity to the airport makes the transfer painless even on arrival/departure days that bookend a longer trip.",
    categories: ["long-stay", "luxury"],
    nights: 15,
    price: 6499,
    currency: "USD",
    priceType: "per-couple",
    rating: 4.6,
    ratingCount: 22,
    highlights: ["Two full weeks at a resort island", "10-minute speedboat from the airport", "PADI Open Water course included"],
    bestFor: ["Long-stay travelers", "Couples"],
    included: ["Accommodation", "Breakfast daily", "PADI Open Water Diver Course"],
    transferIncluded: true,
    transferLabel: "Speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "kurumba-maldives",
    activitySlugs: ["padi-open-water-diver-course"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Speedboat transfer from Velana International Airport." },
      { day: 4, title: "PADI Open Water course begins", description: "Full certification course over several days.", activitySlugs: ["padi-open-water-diver-course"] },
      { day: 10, title: "Midway", description: "Settled into island routine — beach, pool, water sports." },
      { day: 15, title: "Departure", description: "Speedboat transfer back to Velana International Airport." },
    ],
    createdAt: "2026-01-02",
  },
  {
    slug: "maldives-solo-island-explorer-ukulhas",
    title: "Maldives Solo Island Explorer",
    shortDescription: "Seven nights at SeaLaVie Inn on Ukulhas, a laid-back local island in Alif Alif Atoll.",
    description: "Ukulhas is one of the cleaner, more relaxed local islands to visit solo — a proper guesthouse stay with real island life, not a resort bubble.",
    categories: ["solo", "budget"],
    nights: 7,
    price: 999,
    currency: "USD",
    priceType: "per-person",
    rating: 4.4,
    ratingCount: 28,
    highlights: ["A full week on a local island", "Genuinely solo-friendly guesthouse", "Real island life, not a resort bubble"],
    bestFor: ["Solo travelers", "Budget travelers"],
    included: ["Accommodation", "Breakfast daily"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "sealavie-inn",
    itinerary: [
      { day: 1, title: "Arrival", description: "Ferry or speedboat transfer from Malé to Ukulhas." },
      { day: 2, title: "Settle in", description: "Explore the island — it's small enough to walk end to end." },
      { day: 4, title: "Free day", description: "Optional snorkeling trip, arranged locally." },
      { day: 7, title: "Departure", description: "Ferry or speedboat transfer back to Malé." },
    ],
    createdAt: "2026-01-08",
  },
  {
    slug: "adults-only-overwater-retreat-lankanfushi",
    title: "Adults-Focused Overwater Retreat",
    shortDescription: "A quieter, adult-focused six nights at Gili Lankanfushi for travelers wanting a calm, no-schedule stay.",
    description: "Not every trip needs children's activities — this itinerary is built around Gili Lankanfushi's overwater villas and free time, curated for travelers who want peace and quiet above all else.",
    categories: ["adults-only", "luxury"],
    nights: 6,
    price: 4599,
    currency: "USD",
    priceType: "per-couple",
    rating: 4.8,
    ratingCount: 24,
    highlights: ["Overwater villa with private pool", "No structured itinerary — genuinely free time", "20-minute speedboat from the airport"],
    bestFor: ["Couples", "Adults traveling without children"],
    included: ["Accommodation", "Breakfast daily"],
    transferIncluded: true,
    transferLabel: "Speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "gili-lankanfushi",
    itinerary: [
      { day: 1, title: "Arrival", description: "Speedboat transfer from Velana International Airport." },
      { day: 3, title: "Free time", description: "No structured plan — spa, pool, or the villa's own deck." },
      { day: 6, title: "Departure", description: "Speedboat transfer back to Velana International Airport." },
    ],
    createdAt: "2026-01-09",
  },
  {
    slug: "maldives-diving-course-island-stay-maafushi",
    title: "Maldives Diving Course & Island Stay",
    shortDescription: "Six nights on Maafushi with two real diving courses through Kaani Beach Hotel.",
    description: "A budget-friendly, diving-focused itinerary — Advanced Open Water and Night Diver Specialty courses, both genuinely on record at this Maafushi hotel.",
    categories: ["diving", "budget"],
    nights: 6,
    price: 1199,
    currency: "USD",
    priceType: "per-person",
    rating: 4.5,
    ratingCount: 31,
    highlights: ["Advanced Open Water course included", "Night Diver Specialty course included", "Budget local-island base"],
    bestFor: ["Divers", "Budget travelers"],
    included: ["Accommodation", "Breakfast daily", "Advanced Open Water Diver Course", "Night Diver Specialty Course"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "kaani-beach-hotel",
    activitySlugs: ["advanced-open-water-diver-course", "night-diver-specialty-course"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Ferry or speedboat transfer from Malé to Maafushi." },
      { day: 2, title: "Advanced Open Water course", description: "Classroom, pool, and open-water dives.", activitySlugs: ["advanced-open-water-diver-course"] },
      { day: 4, title: "Night Diver Specialty course", description: "Real night dives with a certified instructor.", activitySlugs: ["night-diver-specialty-course"] },
      { day: 6, title: "Departure", description: "Ferry or speedboat transfer back to Malé." },
    ],
    createdAt: "2026-01-10",
  },
  {
    slug: "maldives-diving-discovery-rasdhoo",
    title: "Maldives Diving Discovery",
    shortDescription: "Six nights based near Rasdhoo, Alif Alif Atoll, one of the Maldives' best-known diving hubs.",
    description: "Rasdhoo sits right by the Rasdhoo Madivaru drop-off, one of the country's most famous dive sites — this itinerary anchors at Dhaankolhu Rasdhoo for easy access to real local dive operators.",
    categories: ["diving"],
    nights: 6,
    price: 1399,
    currency: "USD",
    priceType: "per-person",
    rating: 4.6,
    ratingCount: 26,
    highlights: ["Based in one of the Maldives' best-known dive hubs", "Local island budget stay", "Easy access to real dive operators"],
    bestFor: ["Divers", "Budget travelers"],
    included: ["Accommodation", "Breakfast daily"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "dhaankolhu-rasdhoo",
    itinerary: [
      { day: 1, title: "Arrival", description: "Ferry or speedboat transfer from Malé to Rasdhoo." },
      { day: 2, title: "Settle in", description: "Explore the island and arrange dives locally." },
      { day: 4, title: "Diving days", description: "Local dive operators run trips to nearby sites daily." },
      { day: 6, title: "Departure", description: "Ferry or speedboat transfer back to Malé." },
    ],
    createdAt: "2026-01-10",
  },
  {
    slug: "maldives-fishing-adventure-maafushi",
    title: "Maldives Fishing Adventure",
    shortDescription: "Six nights on Maafushi with two real fishing trips through Arena Beach Hotel.",
    description: "A fishing-focused local-island stay — sunset and night fishing trips, both genuinely on record at this Maafushi hotel, without resort-island prices.",
    categories: ["fishing", "budget"],
    nights: 6,
    price: 949,
    currency: "USD",
    priceType: "per-person",
    rating: 4.3,
    ratingCount: 22,
    highlights: ["Sunset fishing trip included", "Night fishing trip included", "Budget local-island base"],
    bestFor: ["Anglers", "Budget travelers"],
    included: ["Accommodation", "Breakfast daily", "Sunset fishing trip", "Night fishing trip"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "arena-beach-hotel",
    activitySlugs: ["sunset-fishing-trip-maafushi", "night-fishing-trip"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Ferry or speedboat transfer from Malé to Maafushi." },
      { day: 2, title: "Sunset fishing trip", description: "A real local sunset fishing trip.", activitySlugs: ["sunset-fishing-trip-maafushi"] },
      { day: 4, title: "Night fishing trip", description: "A night trip targeting different species.", activitySlugs: ["night-fishing-trip"] },
      { day: 6, title: "Departure", description: "Ferry or speedboat transfer back to Malé." },
    ],
    createdAt: "2026-01-11",
  },
  {
    slug: "marlin-big-game-fishing-escape-hulhumale",
    title: "Marlin & Big Game Fishing Escape",
    shortDescription: "Four nights at Coral Grand Beach & Spa on Hulhumalé, with a real marlin and big game charter.",
    description: "Hulhumalé is a short causeway ride from the airport, making it a practical base for a serious fishing charter without the cost of a resort island.",
    categories: ["fishing", "luxury"],
    nights: 4,
    price: 1899,
    currency: "USD",
    priceType: "per-person",
    rating: 4.5,
    ratingCount: 15,
    highlights: ["Marlin & Big Game Fishing Charter included", "Close to the airport", "Real deep-sea sport fishing"],
    bestFor: ["Anglers"],
    included: ["Accommodation", "Breakfast daily", "Marlin & Big Game Fishing Charter"],
    transferIncluded: true,
    transferLabel: "Road transfer",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "coral-grand-beach-spa",
    activitySlugs: ["marlin-big-game-fishing-charter"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Short road transfer from Velana International Airport across the causeway to Hulhumalé." },
      { day: 2, title: "Marlin & Big Game Fishing Charter", description: "A full-day deep-sea charter targeting marlin and other big game.", activitySlugs: ["marlin-big-game-fishing-charter"] },
      { day: 3, title: "Free day", description: "Recover, explore Hulhumalé, or arrange a second charter locally." },
      { day: 4, title: "Departure", description: "Road transfer back to Velana International Airport." },
    ],
    createdAt: "2026-01-11",
  },
  {
    slug: "maldives-surf-island-escape-thulusdhoo",
    title: "Maldives Surf & Island Escape",
    shortDescription: "Eight nights at Go Surf Maldives on Thulusdhoo, one of the country's best-known surf islands.",
    description: "Thulusdhoo sits close to famous breaks like Cokes and Chickens — Go Surf Maldives is a genuine surf-focused guesthouse with real lessons and boat trips already on record.",
    categories: ["surfing", "solo", "budget"],
    nights: 8,
    price: 1499,
    currency: "USD",
    priceType: "per-person",
    rating: 4.6,
    ratingCount: 29,
    highlights: ["Group surf lesson included", "Guided surf boat trip included", "Based on a genuine surf island"],
    bestFor: ["Surfers", "Solo travelers"],
    included: ["Accommodation", "Breakfast daily", "Group surf lesson", "Guided surf boat trip"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "go-surf-maldives",
    activitySlugs: ["group-surf-lesson", "guided-surf-boat-trip"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Ferry or speedboat transfer from Malé to Thulusdhoo." },
      { day: 2, title: "Group surf lesson", description: "An intro lesson in the lagoon for all levels.", activitySlugs: ["group-surf-lesson"] },
      { day: 4, title: "Guided surf boat trip", description: "A boat trip out to nearby breaks with a local guide.", activitySlugs: ["guided-surf-boat-trip"] },
      { day: 8, title: "Departure", description: "Ferry or speedboat transfer back to Malé." },
    ],
    createdAt: "2026-01-12",
  },
  {
    slug: "thulusdhoo-surf-camp",
    title: "Thulusdhoo Surf Camp",
    shortDescription: "Five nights at Go Surf Maldives, a shorter surf-focused stay for a quick trip.",
    description: "A tighter version of the full surf escape — enough time to properly rent a board and get in the water without committing to a full week.",
    categories: ["surfing", "budget"],
    nights: 5,
    price: 899,
    currency: "USD",
    priceType: "per-person",
    rating: 4.4,
    ratingCount: 17,
    highlights: ["Surfboard rental included", "Surf lesson included", "Shorter, budget-friendly surf trip"],
    bestFor: ["Surfers", "Budget travelers"],
    included: ["Accommodation", "Breakfast daily", "Surf lesson", "Surfboard rental"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "go-surf-maldives",
    activitySlugs: ["surf-lesson", "surfboard-rental"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Ferry or speedboat transfer from Malé to Thulusdhoo." },
      { day: 2, title: "Surf lesson", description: "A lesson to start or sharpen your surfing.", activitySlugs: ["surf-lesson"] },
      { day: 3, title: "Free surfing", description: "Rented board, paddle out on your own schedule.", activitySlugs: ["surfboard-rental"] },
      { day: 5, title: "Departure", description: "Ferry or speedboat transfer back to Malé." },
    ],
    createdAt: "2026-01-12",
  },
  {
    slug: "maldives-liveaboard-diving-expedition",
    title: "Maldives Liveaboard Diving Expedition",
    shortDescription: "Seven nights aboard a liveaboard dive vessel exploring Ari Atoll's dive sites.",
    description:
      "Ari Atoll (Alif Alif and Alif Dhaalu) is one of the Maldives' best-known liveaboard diving regions — this itinerary covers a week aboard a dive vessel rather than a single island stay. No specific operator is named here yet; enquire and we'll confirm real vessel and schedule details.",
    categories: ["liveaboard", "diving"],
    nights: 7,
    price: 2799,
    currency: "USD",
    priceType: "per-person",
    rating: 4.7,
    ratingCount: 12,
    highlights: ["A full week living aboard a dive vessel", "Multiple dive sites across Ari Atoll", "Up to 3 dives most days"],
    bestFor: ["Divers", "Solo travelers", "Groups"],
    included: ["Full board while aboard", "Guided dives"],
    transferIncluded: false,
    mealsIncluded: "Full board while aboard",
    flightIncluded: false,
    atollSlug: "alif-alif",
    itinerary: [
      { day: 1, title: "Boarding", description: "Board the vessel in Malé and set out toward Ari Atoll." },
      { day: 2, title: "North Ari dive sites", description: "Diving begins across North Ari Atoll's reefs and channels." },
      { day: 4, title: "South Ari dive sites", description: "The vessel continues into South Ari (Alif Dhaalu) Atoll." },
      { day: 7, title: "Return to Malé", description: "Final dives and return to Malé for disembarkation." },
    ],
    createdAt: "2026-01-13",
  },
  {
    slug: "maldives-local-island-hopping-adventure",
    title: "Maldives Local Island Hopping Adventure",
    shortDescription: "Six nights based on Rasdhoo with day trips to nearby local islands and sandbanks.",
    description: "A budget-friendly way to see more than one island — based on Rasdhoo with real day-trip options to neighbouring local islands, rather than committing to a single spot.",
    categories: ["budget", "solo"],
    nights: 6,
    price: 1099,
    currency: "USD",
    priceType: "per-person",
    rating: 4.3,
    ratingCount: 14,
    highlights: ["Based in a real local island hub", "Day trips to neighbouring islands", "Budget-friendly"],
    bestFor: ["Budget travelers", "Solo travelers"],
    included: ["Accommodation", "Breakfast daily"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "dhaankolhu-rasdhoo",
    itinerary: [
      { day: 1, title: "Arrival", description: "Ferry or speedboat transfer from Malé to Rasdhoo." },
      { day: 3, title: "Island hopping day", description: "A day trip to a neighbouring local island, arranged locally." },
      { day: 5, title: "Sandbank trip", description: "An optional sandbank excursion, arranged locally." },
      { day: 6, title: "Departure", description: "Ferry or speedboat transfer back to Malé." },
    ],
    createdAt: "2026-01-13",
  },
  {
    slug: "extended-soneva-fushi-wellness-retreat",
    title: "Extended Soneva Fushi Wellness Retreat",
    shortDescription: "Ten nights at Soneva Fushi with a focus on rest — the longer version of our luxury escape.",
    description: "The same all-inclusive Soneva Fushi base as our shorter luxury escape, extended to ten nights for travelers who want the private-island quiet to actually sink in.",
    categories: ["long-stay", "luxury", "honeymoon"],
    nights: 10,
    price: 7599,
    currency: "USD",
    priceType: "per-couple",
    rating: 4.9,
    ratingCount: 18,
    highlights: ["Ten nights all-inclusive", "Guided reef dive included", "Genuinely private island"],
    bestFor: ["Couples", "Long-stay travelers", "Luxury travelers"],
    included: ["Accommodation", "All meals", "Guided reef dive", "Return seaplane transfer"],
    transferIncluded: true,
    transferLabel: "Seaplane",
    mealsIncluded: "All meals",
    flightIncluded: false,
    accommodationSlug: "soneva-fushi",
    activitySlugs: ["guided-reef-dive"],
    itinerary: [
      { day: 1, title: "Arrival & seaplane transfer", description: "Seaplane transfer from Velana International Airport straight to the resort." },
      { day: 4, title: "Guided reef dive", description: "A guided reef dive through the resort's own dive centre.", activitySlugs: ["guided-reef-dive"] },
      { day: 7, title: "Midway", description: "Fully settled into island time by now." },
      { day: 10, title: "Departure", description: "Seaplane transfer back to Velana International Airport." },
    ],
    createdAt: "2026-01-01",
  },
  {
    slug: "family-local-island-holiday-gulhi",
    title: "Family Local Island Holiday",
    shortDescription: "Six nights at Crystal View Maldives Guest House on Gulhi — a budget-friendly family base.",
    description: "A genuinely affordable family option — a real local-island guesthouse on Gulhi rather than an expensive resort, with the beach and reef right there for kids to enjoy.",
    categories: ["family", "budget"],
    nights: 6,
    price: 1399,
    currency: "USD",
    priceType: "per-package",
    rating: 4.2,
    ratingCount: 11,
    highlights: ["Budget-friendly family base", "Local island beach access", "Quiet island, easy to manage with kids"],
    bestFor: ["Families", "Budget travelers"],
    included: ["Accommodation", "Breakfast daily"],
    transferIncluded: true,
    transferLabel: "Public ferry or speedboat",
    mealsIncluded: "Breakfast daily",
    flightIncluded: false,
    accommodationSlug: "crystal-view-maldives-guest-house",
    itinerary: [
      { day: 1, title: "Arrival", description: "Ferry or speedboat transfer from Malé to Gulhi." },
      { day: 2, title: "Settle in", description: "Beach time and getting to know the island." },
      { day: 4, title: "Free day", description: "Optional family snorkeling trip, arranged locally." },
      { day: 6, title: "Departure", description: "Ferry or speedboat transfer back to Malé." },
    ],
    createdAt: "2026-01-14",
  },
];
